import React, { createContext, useContext, useState, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'bn' | 'gu' | 'pa';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Utility Header
    'gov_india': 'Government of India',
    'bharat_sarkar': 'भारत सरकार',
    'skip_to_content': 'Skip to main content',
    'screen_reader': 'Screen Reader Access',
    'sitemap': 'Sitemap',
    'faqs': 'FAQs',
    'helpdesk': 'Helpdesk',
    'contact_us': 'Contact Us',

    // Branding Header
    'mplads_title_1': 'Members of Parliament',
    'mplads_title_2': 'Local Area Development Scheme (MPLADS)',
    'mospi_dept': 'Ministry of Statistics & Programme Implementation',
    'gov_of_india_sub': 'Government of India',
    'motto_1': 'Sabka Saath',
    'motto_2': 'Sabka Vikas',
    'motto_3': 'Sabka Vishwas',
    'motto_4': 'Sabka Prayas',

    // Navigation Menu
    'nav_home': 'Home',
    'nav_about': 'About MPLADS',
    'nav_mps': 'MPs',
    'nav_projects': 'Projects',
    'nav_tenders': 'Tenders & Contracts',
    'nav_vendors': 'Vendors',
    'nav_funds': 'Fund Management',
    'nav_reports': 'Reports',
    'nav_rural_intelligence': 'Rural Intelligence',
    'nav_contractor_opportunities': 'Contractor Opportunities',
    'nav_ai_insights': 'AI Insights',
    'nav_citizen': 'Citizen Corner',
    'search_placeholder': 'Search projects, contractors, tenders...',

    // Hero Section
    'pm_quote': '“Development works under MPLADS strengthen the foundation of a New India by empowering local communities.”',
    'pm_name': 'Narendra Modi',
    'pm_designation': 'Prime Minister of India',
    'peoples_vision': "People's Vision",
    'projects_for_progress': 'Projects for Progress',
    'pillar_transparency': 'Transparency',
    'pillar_accountability': 'Accountability',
    'pillar_inclusive': 'Inclusive Development',
    'pillar_lasting_assets': 'Lasting Assets',

    // Role Selector
    'role_overview': 'Overview',
    'role_mp': 'MP View',
    'role_district': 'District Authority',
    'role_contractor': 'Contractor',
    'role_vendor': 'Vendor',
    'role_ministry': 'Ministry',
    'role_citizen': 'Citizen View',
    'district_auth_name': 'Farea Ansari',
    'district_auth_loc': 'District Authority, Mumbai',

    // Map & Stats
    'total_mps': 'Total MPs',
    'total_projects': 'Total Projects',
    'sanctioned_amount': 'Sanctioned Amount',
    'contracts_awarded': 'Contracts Awarded',
    'works_completed': 'Works Completed',
    'in_progress': 'In Progress',
    'delayed': 'Delayed',
    'high_risk': 'High Risk',
    'project_map_india': 'Project Map – India',
    'fund_utilization': 'Fund Utilization',
    'recent_projects': 'Recent Projects',
    'vendor_marketplace': 'Vendor Marketplace',
  },
  hi: {
    // Utility Header
    'gov_india': 'Government of India',
    'bharat_sarkar': 'भारत सरकार',
    'skip_to_content': 'मुख्य सामग्री पर जाएं',
    'screen_reader': 'स्क्रीन रीडर एक्सेस',
    'sitemap': 'साइटमैप',
    'faqs': 'अक्सर पूछे जाने वाले प्रश्न',
    'helpdesk': 'हेल्पडेस्क',
    'contact_us': 'संपर्क करें',

    // Branding Header
    'mplads_title_1': 'संसद सदस्य',
    'mplads_title_2': 'स्थानीय क्षेत्र विकास योजना (एमपीलैड्स)',
    'mospi_dept': 'सांख्यिकी और कार्यक्रम कार्यान्वयन मंत्रालय',
    'gov_of_india_sub': 'भारत सरकार',
    'motto_1': 'सबका साथ',
    'motto_2': 'सबका विकास',
    'motto_3': 'सबका विश्वास',
    'motto_4': 'सबका प्रयास',

    // Navigation Menu
    'nav_home': 'मुख्य पृष्ठ',
    'nav_about': 'एमपीलैड्स के बारे में',
    'nav_mps': 'सांसद',
    'nav_projects': 'परियोजनाएं',
    'nav_tenders': 'निविदाएं और अनुबंध',
    'nav_vendors': 'विक्रेता',
    'nav_funds': 'निधि प्रबंधन',
    'nav_reports': 'रिपोर्ट',
    'nav_ai_insights': 'एआई अंतर्दृष्टि',
    'nav_citizen': 'नागरिक कोना',
    'search_placeholder': 'परियोजनाएं, ठेकेदार, निविदाएं खोजें...',

    // Hero Section
    'pm_quote': '“एमपीलैड्स के तहत विकास कार्य स्थानीय समुदायों को सशक्त बनाकर नए भारत की नींव को मजबूत करते हैं।”',
    'pm_name': 'नरेन्द्र मोदी',
    'pm_designation': 'प्रधानमंत्री, भारत सरकार',
    'peoples_vision': 'जन-जन का संकल्प',
    'projects_for_progress': 'प्रगति के लिए परियोजनाएं',
    'pillar_transparency': 'पारदर्शिता',
    'pillar_accountability': 'जवाबदेही',
    'pillar_inclusive': 'समावेशी विकास',
    'pillar_lasting_assets': 'स्थायी संपत्ति',

    // Role Selector
    'role_overview': 'अवलोकन',
    'role_mp': 'सांसद दृश्य',
    'role_district': 'जिला प्राधिकरण',
    'role_contractor': 'ठेकेदार',
    'role_vendor': 'विक्रेता',
    'role_ministry': 'मंत्रालय',
    'role_citizen': 'नागरिक दृश्य',
    'district_auth_name': 'फरिया अंसारी',
    'district_auth_loc': 'जिला प्राधिकरण, मुंबई',

    // Map & Stats
    'total_mps': 'कुल सांसद',
    'total_projects': 'कुल परियोजनाएं',
    'sanctioned_amount': 'स्वीकृत राशि',
    'contracts_awarded': 'अनुबंधित कार्य',
    'works_completed': 'पूर्ण कार्य',
    'in_progress': 'प्रगति में',
    'delayed': 'विलंबित',
    'high_risk': 'उच्च जोखिम',
    'project_map_india': 'परियोजना मानचित्र – भारत',
    'fund_utilization': 'निधि उपयोग',
    'recent_projects': 'हाल की परियोजनाएं',
    'vendor_marketplace': 'विक्रेता बाज़ार',
  },
  mr: {
    'gov_india': 'Government of India',
    'bharat_sarkar': 'भारत सरकार',
    'skip_to_content': 'मुख्य सामग्रीकडे जा',
    'screen_reader': 'स्क्रीन रीडर प्रवेश',
    'sitemap': 'साइटमॅप',
    'faqs': 'नेहमी विचारले जाणारे प्रश्न',
    'helpdesk': 'मदत केंद्र',
    'contact_us': 'संपर्क साधा',
    'mplads_title_1': 'खासदार',
    'mplads_title_2': 'स्थानिक क्षेत्र विकास योजना (MPLADS)',
    'mospi_dept': 'सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय',
    'gov_of_india_sub': 'भारत सरकार',
    'motto_1': 'सबका साथ',
    'motto_2': 'सबका विकास',
    'motto_3': 'सबका विश्वास',
    'motto_4': 'सबका प्रयास',
    'nav_home': 'मुख्य पृष्ठ',
    'nav_about': 'MPLADS बद्दल',
    'nav_mps': 'खासदार',
    'nav_projects': 'प्रकल्प',
    'nav_tenders': 'निविदा आणि कंत्राटे',
    'nav_vendors': 'विक्रेते',
    'nav_funds': 'निधी व्यवस्थापन',
    'nav_reports': 'अहवाल',
    'nav_ai_insights': 'AI अंतर्दृष्टी',
    'nav_citizen': 'नागरिक विभाग',
    'search_placeholder': 'प्रकल्प, कंत्राटदार, निविदा शोधा...',
    'pm_quote': '“MPLADS अंतर्गत विकासकामे स्थानिक समुदायांना सक्षम करून नव्या भारताचा पाया मजबूत करतात.”',
    'pm_name': 'नरेंद्र मोदी',
    'pm_designation': 'पंतप्रधान, भारत',
    'peoples_vision': 'जनतेचा दृष्टीकोन',
    'projects_for_progress': 'प्रगतीसाठी प्रकल्प',
    'pillar_transparency': 'पारदर्शकता',
    'pillar_accountability': 'जबाबदारी',
    'pillar_inclusive': 'समावेशक विकास',
    'pillar_lasting_assets': 'शाश्वत मालमत्ता',
    'role_overview': 'आढावा',
    'role_mp': 'खासदार दृश्य',
    'role_district': 'जिल्हा प्राधिकरण',
    'role_contractor': 'कंत्राटदार',
    'role_vendor': 'विक्रेता',
    'role_ministry': 'मंत्रालय',
    'role_citizen': 'नागरिक दृश्य',
    'district_auth_name': 'फरिया अंसारी',
    'district_auth_loc': 'जिल्हा प्राधिकरण, मुंबई',
    'total_mps': 'एकूण खासदार',
    'total_projects': 'एकूण प्रकल्प',
    'sanctioned_amount': 'मंजूर रक्कम',
    'contracts_awarded': 'दिलेली कंत्राटे',
    'works_completed': 'पूर्ण झालेली कामे',
    'in_progress': 'प्रगतीपथावर',
    'delayed': 'विलंबित',
    'high_risk': 'उच्च जोखीम',
    'project_map_india': 'प्रकल्प नकाशा – भारत',
    'fund_utilization': 'निधी वापर',
    'recent_projects': 'नुकतेच प्रकल्प',
    'vendor_marketplace': 'विक्रेता बाजार',
  },
  ta: {
    'gov_india': 'Government of India',
    'bharat_sarkar': 'இந்திய அரசு',
    'skip_to_content': 'முக்கிய உள்ளடக்கத்திற்குச் செல்க',
    'screen_reader': 'திரை வாசிப்பான் அணுகல்',
    'sitemap': 'தள வரைபடம்',
    'faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'helpdesk': 'உதவி மையம்',
    'contact_us': 'தொடர்பு கொள்ள',
    'mplads_title_1': 'நாடாளுமன்ற உறுப்பினர்கள்',
    'mplads_title_2': 'தொகுதி மேம்பாட்டுத் திட்டம் (MPLADS)',
    'mospi_dept': 'புள்ளியியல் மற்றும் திட்ட அமலாக்க அமைச்சகம்',
    'gov_of_india_sub': 'இந்திய அரசு',
    'motto_1': 'அனைவருடனும்',
    'motto_2': 'அனைவருக்குமான வளர்ச்சி',
    'motto_3': 'அனைவரின் நம்பிக்கை',
    'motto_4': 'அனைவரின் முயற்சி',
    'nav_home': 'முகப்பு',
    'nav_about': 'MPLADS பற்றி',
    'nav_mps': 'எம்.பி.க்கள்',
    'nav_projects': 'திட்டங்கள்',
    'nav_tenders': 'டெண்டர்கள் & ஒப்பந்தங்கள்',
    'nav_vendors': 'விற்பனையாளர்கள்',
    'nav_funds': 'நிதி மேலாண்மை',
    'nav_reports': 'அறிக்கைகள்',
    'nav_ai_insights': 'AI நுண்ணறிவு',
    'nav_citizen': 'குடிமக்கள் பகுதி',
    'search_placeholder': 'திட்டங்கள், ஒப்பந்ததாரர்கள், டெண்டர்களைத் தேடுங்கள்...',
    'pm_quote': '“MPLADS திட்டத்தின் கீழ் மேற்கொள்ளப்படும் வளர்ச்சிப் பணிகள் புதிய இந்தியாவின் அடித்தளத்தை வலுப்படுத்துகின்றன.”',
    'pm_name': 'நரேந்திர மோடி',
    'pm_designation': 'இந்தியப் பிரதமர்',
    'peoples_vision': 'மக்கள் பார்வை',
    'projects_for_progress': 'முன்னேற்றத்திற்கான திட்டங்கள்',
    'pillar_transparency': 'வெளிப்படைத்தன்மை',
    'pillar_accountability': 'பொறுப்புடைமை',
    'pillar_inclusive': 'உள்ளடக்கிய வளர்ச்சி',
    'pillar_lasting_assets': 'நிலையான சொத்துக்கள்',
    'role_overview': 'மேலோட்டம்',
    'role_mp': 'எம்.பி பார்வை',
    'role_district': 'மாவட்ட அதிகாரம்',
    'role_contractor': 'ஒப்பந்ததாரர்',
    'role_vendor': 'விற்பனையாளர்',
    'role_ministry': 'அமைச்சகம்',
    'role_citizen': 'குடிமக்கள் பார்வை',
    'district_auth_name': 'ஃபரியா அன்சாரி',
    'district_auth_loc': 'மாவட்ட அதிகாரம், மும்பை',
    'total_mps': 'மொத்த எம்.பி.க்கள்',
    'total_projects': 'மொத்த திட்டங்கள்',
    'sanctioned_amount': 'ஒதுக்கப்பட்ட தொகை',
    'contracts_awarded': 'வழங்கப்பட்ட ஒப்பந்தங்கள்',
    'works_completed': 'முடிக்கப்பட்ட பணிகள்',
    'in_progress': 'செயல்பாட்டில்',
    'delayed': 'தாமதமானது',
    'high_risk': 'அதிக ஆபத்து',
    'project_map_india': 'திட்ட வரைபடம் – இந்தியா',
    'fund_utilization': 'நிதி பயன்பாடு',
    'recent_projects': 'சமீபத்திய திட்டங்கள்',
    'vendor_marketplace': 'விற்பனையாளர் சந்தை',
  },
  te: {
    'gov_india': 'Government of India',
    'bharat_sarkar': 'భారత ప్రభుత్వం',
    'skip_to_content': 'ప్రధాన కంటెంట్‌కు వెళ్లండి',
    'screen_reader': 'స్క్రీన్ రీడర్ యాక్సెస్',
    'sitemap': 'సైట్‌మ్యాప్',
    'faqs': 'తరచుగా అడిగే ప్రశ్నలు',
    'helpdesk': 'సహాయ కేంద్రం',
    'contact_us': 'మమ్మల్ని సంప్రదించండి',
    'mplads_title_1': 'పార్లమెంటు సభ్యులు',
    'mplads_title_2': 'స్థానిక ప్రాంత అభివృద్ధి పథకం (MPLADS)',
    'mospi_dept': 'గణాంకాలు మరియు కార్యక్రమ అమలు మంత్రిత్వ శాఖ',
    'gov_of_india_sub': 'భారత ప్రభుత్వం',
    'motto_1': 'సబ్‌కా సాథ్',
    'motto_2': 'సబ్‌కా వికాస్',
    'motto_3': 'సబ్‌కా విశ్వాస్',
    'motto_4': 'సబ్‌కా ప్రయాస్',
    'nav_home': 'హోమ్',
    'nav_about': 'MPLADS గురించి',
    'nav_mps': 'ఎంపీలు',
    'nav_projects': 'ప్రాజెక్ట్‌లు',
    'nav_tenders': 'టెండర్లు & ఒప్పందాలు',
    'nav_vendors': 'విక్రేతలు',
    'nav_funds': 'నిధుల నిర్వహణ',
    'nav_reports': 'నివేదికలు',
    'nav_ai_insights': 'AI ఇన్‌సైట్‌లు',
    'nav_citizen': 'పౌరుల వేదిక',
    'search_placeholder': 'ప్రాజెక్ట్‌లు, కాంట్రాక్టర్లు, టెండర్లను శోధించండి...',
    'pm_quote': '“MPLADS కింద అభివృద్ధి పనులు స్థానిక కమ్యూనిటీలను శక్తివంతం చేయడం ద్వారా నవ భారతానికి బలమైన పునాదిని వేస్తాయి.”',
    'pm_name': 'నరేంద్ర మోదీ',
    'pm_designation': 'భారత ప్రధాని',
    'peoples_vision': 'ప్రజల దార్శనికత',
    'projects_for_progress': 'పురోగతి కోసం ప్రాజెక్టులు',
    'pillar_transparency': 'పారదర్శకత',
    'pillar_accountability': 'బాధ్యతాయుతత్వం',
    'pillar_inclusive': 'సమ్మిళిత అభివృద్ధి',
    'pillar_lasting_assets': 'శాశ్వత ఆస్తులు',
    'role_overview': 'సమీక్ష',
    'role_mp': 'ఎంపీ వీక్షణ',
    'role_district': 'జిల్లా అధికారం',
    'role_contractor': 'కాంట్రాక్టర్',
    'role_vendor': 'విక్రేత',
    'role_ministry': 'మంత్రిత్వ శాఖ',
    'role_citizen': 'పౌరుల వీక్షణ',
    'district_auth_name': 'ఫరియా అన్సారీ',
    'district_auth_loc': 'జిల్లా అధికారం, ముంబై',
    'total_mps': 'మొత్తం ఎంపీలు',
    'total_projects': 'మొత్తం ప్రాజెక్ట్‌లు',
    'sanctioned_amount': 'మంజూరైన మొత్తం',
    'contracts_awarded': 'కేటాయించిన కాంట్రాక్టులు',
    'works_completed': 'పూర్తయిన పనులు',
    'in_progress': 'పురోగతిలో ఉంది',
    'delayed': 'ఆలస్యమైంది',
    'high_risk': 'అధిక ప్రమాదం',
    'project_map_india': 'ప్రాజెక్ట్ మ్యాప్ – భారతదేశం',
    'fund_utilization': 'నిధుల వినియోగం',
    'recent_projects': 'ఇటీవలి ప్రాజెక్ట్‌లు',
    'vendor_marketplace': 'విక్రేతల మార్కెట్',
  },
  bn: {
    'gov_india': 'Government of India',
    'bharat_sarkar': 'ভারত সরকার',
    'skip_to_content': 'মূল বিষয়বস্তুতে যান',
    'screen_reader': 'স্ক্রিন রিডার অ্যাক্সেস',
    'sitemap': 'সাইটম্যাপ',
    'faqs': 'সাধারণ প্রশ্নাবলী',
    'helpdesk': 'হেল্পডেস্ক',
    'contact_us': 'যোগাযোগ করুন',
    'mplads_title_1': 'সংসদ সদস্য',
    'mplads_title_2': 'স্থানীয় এলাকা উন্নয়ন প্রকল্প (MPLADS)',
    'mospi_dept': 'পরিসংখ্যান ও কর্মসূচি বাস্তবায়ন মন্ত্রণালয়',
    'gov_of_india_sub': 'ভারত সরকার',
    'motto_1': 'সবকা সাথ',
    'motto_2': 'সবকা বিকাশ',
    'motto_3': 'সবকা বিশ্বাস',
    'motto_4': 'সবকা প্রয়াস',
    'nav_home': 'হোম',
    'nav_about': 'MPLADS সম্পর্কে',
    'nav_mps': 'সাংসদগণ',
    'nav_projects': 'প্রকল্পসমূহ',
    'nav_tenders': 'টেন্ডার ও চুক্তি',
    'nav_vendors': 'বিক্রেতা',
    'nav_funds': 'তহবিল ব্যবস্থাপনা',
    'nav_reports': 'প্রতিবেদন',
    'nav_ai_insights': 'AI অন্তর্দৃষ্টি',
    'nav_citizen': 'নাগরিক কর্নার',
    'search_placeholder': 'প্রকল্প, ঠিকাদার, টেন্ডার অনুসন্ধান করুন...',
    'pm_quote': '“MPLADS-এর অধীনে উন্নয়নমূলক কাজ স্থানীয় সম্প্রদায়কে ক্ষমতায়িত করে নতুন ভারতের ভিত্তি মজবুত করে।”',
    'pm_name': 'নরেন্দ্র মোদী',
    'pm_designation': 'ভারতের প্রধানমন্ত্রী',
    'peoples_vision': 'জনগণের দৃষ্টিভঙ্গি',
    'projects_for_progress': 'অগ্রগতির জন্য প্রকল্প',
    'pillar_transparency': 'স্বচ্ছতা',
    'pillar_accountability': 'দায়বদ্ধতা',
    'pillar_inclusive': 'অন্তর্ভুক্তিমূলক উন্নয়ন',
    'pillar_lasting_assets': 'স্থায়ী সম্পদ',
    'role_overview': 'সারসংক্ষেপ',
    'role_mp': 'সাংসদ দৃশ্য',
    'role_district': 'জেলা কর্তৃপক্ষ',
    'role_contractor': 'ঠিকাদার',
    'role_vendor': 'বিক্রেতা',
    'role_ministry': 'মন্ত্রণালয়',
    'role_citizen': 'নাগরিক দৃশ্য',
    'district_auth_name': 'ফারিয়া আনসারি',
    'district_auth_loc': 'জেলা কর্তৃপক্ষ, মুম্বাই',
    'total_mps': 'মোট সাংসদ',
    'total_projects': 'মোট প্রকল্প',
    'sanctioned_amount': 'অনুমোদিত পরিমাণ',
    'contracts_awarded': 'প্রদত্ত চুক্তি',
    'works_completed': 'সম্পন্ন কাজ',
    'in_progress': 'চলমান',
    'delayed': 'বিলম্বিত',
    'high_risk': 'উচ্চ ঝুঁকি',
    'project_map_india': 'প্রকল্প মানচিত্র – ভারত',
    'fund_utilization': 'তহবিল ব্যবহার',
    'recent_projects': 'সাম্প্রতিক প্রকল্প',
    'vendor_marketplace': 'বিক্রেতা বাজার',
  },
  gu: {
    'gov_india': 'Government of India',
    'bharat_sarkar': 'ભારત સરકાર',
    'skip_to_content': 'મુખ્ય સામગ્રી પર જાઓ',
    'screen_reader': 'સ્ક્રીન રીડર ઍક્સેસ',
    'sitemap': 'સાઇટમેપ',
    'faqs': 'વારંવાર પૂછાતા પ્રશ્નો',
    'helpdesk': 'હેલ્પડેસ્ક',
    'contact_us': 'સંપર્ક કરો',
    'mplads_title_1': 'સંસદ સભ્ય',
    'mplads_title_2': 'સ્થાનિક વિસ્તાર વિકાસ યોજના (MPLADS)',
    'mospi_dept': 'આંકડા અને કાર્યક્રમ અમલીકરણ મંત્રાલય',
    'gov_of_india_sub': 'ભારત સરકાર',
    'motto_1': 'સબકા સાથ',
    'motto_2': 'સબકા વિકાસ',
    'motto_3': 'સબકા વિશ્વાસ',
    'motto_4': 'સબકા પ્રયાસ',
    'nav_home': 'હોમ',
    'nav_about': 'MPLADS વિશે',
    'nav_mps': 'સાંસદો',
    'nav_projects': 'પ્રોજેક્ટ્સ',
    'nav_tenders': 'ટેન્ડર અને કરારો',
    'nav_vendors': 'વિક્રેતાઓ',
    'nav_funds': 'ફંડ મેનેજમેન્ટ',
    'nav_reports': 'અહેવાલો',
    'nav_ai_insights': 'AI ઇનસાઇટ્સ',
    'nav_citizen': 'નાગરિક કોર્નર',
    'search_placeholder': 'પ્રોજેક્ટ્સ, કોન્ટ્રાક્ટરો, ટેન્ડરો શોધો...',
    'pm_quote': '“MPLADS હેઠળ વિકાસ કાર્યો સ્થાનિક સમુદાયોને સશક્ત બનાવીને નવા ભારતનો પાયો મજબૂત કરે છે.”',
    'pm_name': 'નરેન્દ્ર મોદી',
    'pm_designation': 'ભારતના વડાપ્રધાન',
    'peoples_vision': 'જનતાનો સંકલ્પ',
    'projects_for_progress': 'પ્રગતિ માટે પ્રોજેક્ટ્સ',
    'pillar_transparency': 'પારદર્શિતા',
    'pillar_accountability': 'જવાબદારી',
    'pillar_inclusive': 'સમાવેશી વિકાસ',
    'pillar_lasting_assets': 'કાયમી સંપત્તિ',
    'role_overview': 'ઝાંખી',
    'role_mp': 'સાંસદ દૃશ્ય',
    'role_district': 'જિલ્લા સત્તામંડળ',
    'role_contractor': 'કોન્ટ્રાક્ટર',
    'role_vendor': 'વિક્રેતા',
    'role_ministry': 'મંત્રાલય',
    'role_citizen': 'નાગરિક દૃશ્ય',
    'district_auth_name': 'ફરિયા અંસારી',
    'district_auth_loc': 'જિલ્લા સત્તામંડળ, મુંબઈ',
    'total_mps': 'કુલ સાંસદો',
    'total_projects': 'કુલ પ્રોજેક્ટ્સ',
    'sanctioned_amount': 'મંજૂર રકમ',
    'contracts_awarded': 'આપેલા કરારો',
    'works_completed': 'પૂર્ણ થયેલા કામો',
    'in_progress': 'ચાલુ છે',
    'delayed': 'વિલંબિત',
    'high_risk': 'ઉચ્ચ જોખમ',
    'project_map_india': 'પ્રોજેક્ટ નકશો – ભારત',
    'fund_utilization': 'ફંડ ઉપયોગ',
    'recent_projects': 'તાજેતરના પ્રોજેક્ટ્સ',
    'vendor_marketplace': 'વિક્રેતા બજાર',
  },
  pa: {
    'gov_india': 'Government of India',
    'bharat_sarkar': 'ਭਾਰਤ ਸਰਕਾਰ',
    'skip_to_content': 'ਮੁੱਖ ਸਮੱਗਰੀ ਤੇ ਜਾਓ',
    'screen_reader': 'ਸਕ੍ਰੀਨ ਰੀਡਰ ਪਹੁੰਚ',
    'sitemap': 'ਸਾਈਟਮੈਪ',
    'faqs': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
    'helpdesk': 'ਹੈਲਪਡੈਸਕ',
    'contact_us': 'ਸੰਪਰਕ ਕਰੋ',
    'mplads_title_1': 'ਸੰਸਦ ਮੈਂਬਰ',
    'mplads_title_2': 'ਸਥਾਨਕ ਖੇਤਰ ਵਿਕਾਸ ਸਕੀਮ (MPLADS)',
    'mospi_dept': 'ਅੰਕੜਾ ਅਤੇ ਪ੍ਰੋਗਰਾਮ ਲਾਗੂਕਰਨ ਮੰਤਰਾਲਾ',
    'gov_of_india_sub': 'ਭਾਰਤ ਸਰਕਾਰ',
    'motto_1': 'ਸਭਕਾ ਸਾਥ',
    'motto_2': 'ਸਭਕਾ ਵਿਕਾਸ',
    'motto_3': 'ਸਭਕਾ ਵਿਸ਼ਵਾਸ',
    'motto_4': 'ਸਭਕਾ ਪ੍ਰਯਾਸ',
    'nav_home': 'ਮੁੱਖ ਪੰਨਾ',
    'nav_about': 'MPLADS ਬਾਰੇ',
    'nav_mps': 'ਸੰਸਦ ਮੈਂਬਰ',
    'nav_projects': 'ਪ੍ਰੋਜੈਕਟ',
    'nav_tenders': 'ਟੈਂਡਰ ਅਤੇ ਇਕਰਾਰਨਾਮੇ',
    'nav_vendors': 'ਵਿਕਰੇਤਾ',
    'nav_funds': 'ਫੰਡ ਪ੍ਰਬੰਧਨ',
    'nav_reports': 'ਰਿਪੋਰਟਾਂ',
    'nav_ai_insights': 'AI ਇਨਸਾਈਟਸ',
    'nav_citizen': 'ਨਾਗਰਿਕ ਕੋਨਾ',
    'search_placeholder': 'ਪ੍ਰੋਜੈਕਟ, ਠੇਕੇਦਾਰ, ਟੈਂਡਰ ਖੋਜੋ...',
    'pm_quote': '“MPLADS ਅਧੀਨ ਵਿਕਾਸ ਕਾਰਜ ਸਥਾਨਕ ਭਾਈਚਾਰਿਆਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾ ਕੇ ਨਵੇਂ ਭਾਰਤ ਦੀ ਨੀਂਹ ਨੂੰ ਮਜ਼ਬੂਤ ​​ਕਰਦੇ ਹਨ।”',
    'pm_name': 'ਨਰਿੰਦਰ ਮੋਦੀ',
    'pm_designation': 'ਭਾਰਤ ਦੇ ਪ੍ਰਧਾਨ ਮੰਤਰੀ',
    'peoples_vision': 'ਜਨਤਾ ਦਾ ਸੰਕਲਪ',
    'projects_for_progress': 'ਤਰੱਕੀ ਲਈ ਪ੍ਰੋਜੈਕਟ',
    'pillar_transparency': 'ਪਾਰਦਰਸ਼ਤਾ',
    'pillar_accountability': 'ਜਵਾਬਦੇਹੀ',
    'pillar_inclusive': 'ਸਮਾਵੇਸ਼ੀ ਵਿਕਾਸ',
    'pillar_lasting_assets': 'ਸਥਾਈ ਸੰਪਤੀ',
    'role_overview': 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    'role_mp': 'ਸੰਸਦ ਮੈਂਬਰ ਦ੍ਰਿਸ਼',
    'role_district': 'ਜ਼ਿਲ੍ਹਾ ਅਥਾਰਟੀ',
    'role_contractor': 'ਠੇਕੇਦਾਰ',
    'role_vendor': 'ਵਿਕਰੇਤਾ',
    'role_ministry': 'ਮੰਤਰਾਲਾ',
    'role_citizen': 'ਨਾਗਰਿਕ ਦ੍ਰਿਸ਼',
    'district_auth_name': 'ਫਰੀਆ ਅੰਸਾਰੀ',
    'district_auth_loc': 'ਜ਼ਿਲ੍ਹਾ ਅਥਾਰਟੀ, ਮੁੰਬਈ',
    'total_mps': 'ਕੁੱਲ ਸੰਸਦ ਮੈਂਬਰ',
    'total_projects': 'ਕੁੱਲ ਪ੍ਰੋਜੈਕਟ',
    'sanctioned_amount': 'ਮਨਜ਼ੂਰ ਰਕਮ',
    'contracts_awarded': 'ਦਿੱਤੇ ਗਏ ਠੇਕੇ',
    'works_completed': 'ਮੁਕੰਮਲ ਕੰਮ',
    'in_progress': 'ਪ੍ਰਗਤੀ ਅਧੀਨ',
    'delayed': 'ਦੇਰੀ ਨਾਲ',
    'high_risk': 'ਉੱਚ ਜੋਖਮ',
    'project_map_india': 'ਪ੍ਰੋਜੈਕਟ ਨਕਸ਼ਾ – ਭਾਰਤ',
    'fund_utilization': 'ਫੰਡ ਵਰਤੋਂ',
    'recent_projects': 'ਹਾਲੀਆ ਪ੍ਰੋਜੈਕਟ',
    'vendor_marketplace': 'ਵਿਕਰੇਤਾ ਬਾਜ਼ਾਰ',
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('mplads_lang');
    return (saved as SupportedLanguage) || 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('mplads_lang', lang);
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
