import React, { createContext, useContext, useState, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'bn' | 'gu' | 'pa';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  "en": {
    "gov_india": "Government of India",
    "bharat_sarkar": "भारत सरकार",
    "skip_to_content": "Skip to main content",
    "sitemap": "Sitemap",
    "faqs": "FAQs",
    "helpdesk": "Helpdesk",
    "contact_us": "Contact Us",
    "mplads_title_1": "Members of Parliament",
    "mplads_title_2": "Local Area Development Scheme (MPLADS)",
    "mospi_dept": "Ministry of Statistics & Programme Implementation",
    "gov_of_india_sub": "Government of India",
    "motto_1": "Sabka Saath",
    "motto_2": "Sabka Vikas",
    "motto_3": "Sabka Vishwas",
    "motto_4": "Sabka Prayas",
    "nav_home": "Home",
    "nav_about": "About MPLADS",
    "nav_mps": "MPs",
    "nav_projects": "Projects",
    "nav_tenders": "Tenders & Contracts",
    "nav_vendors": "Vendors",
    "nav_funds": "Fund Management",
    "nav_reports": "Reports",
    "nav_rural_intelligence": "Rural Intelligence",
    "nav_contractor_opportunities": "Contractor Opportunities",
    "nav_ai_insights": "AI Insights",
    "nav_citizen": "Citizen Corner",
    "search_placeholder": "Search projects, contractors, tenders...",
    "pm_quote": "“Development works under MPLADS must ensure equitable progress, democratic accountability, and direct empowerment for every citizen at the grassroots.”",
    "pm_name": "Rahul Gandhi",
    "pm_designation": "Leader of Opposition (LoP), Lok Sabha",
    "lop_quote": "“Development works under MPLADS must ensure equitable progress, democratic accountability, and direct empowerment for every citizen at the grassroots.”",
    "lop_name": "Rahul Gandhi",
    "lop_designation": "Leader of Opposition (LoP), Lok Sabha",
    "peoples_vision": "People's Vision",
    "projects_for_progress": "Projects for Progress",
    "pillar_transparency": "Transparency",
    "pillar_accountability": "Accountability",
    "pillar_inclusive": "Inclusive Development",
    "pillar_lasting_assets": "Lasting Assets",
    "role_overview": "Overview",
    "role_mp": "MP View",
    "role_district": "District Authority",
    "role_contractor": "Contractor",
    "role_vendor": "Vendor",
    "role_ministry": "Ministry",
    "role_citizen": "Citizen View",
    "district_auth_loc": "District Authority, Mumbai",
    "total_mps": "Total MPs",
    "total_projects": "Total Projects",
    "sanctioned_amount": "Sanctioned Amount",
    "contracts_awarded": "Contracts Awarded",
    "works_completed": "Works Completed",
    "in_progress": "In Progress",
    "delayed": "Delayed",
    "high_risk": "High Risk",
    "project_map_india": "Project Map – India",
    "fund_utilization": "Fund Utilization",
    "recent_projects": "Recent Projects",
    "vendor_marketplace": "Vendor Marketplace",
    "all_india": "All India",
    "view_mps": "View MPs",
    "all_years": "All Years",
    "view_projects": "View Projects",
    "view_financials": "View Financials",
    "view_contracts": "View Contracts",
    "view_details": "View Details",
    "completed": "Completed",
    "view_assets": "View Assets",
    "view_delayed": "View Delayed",
    "view_all": "View All",
    "view": "View",
    "investigate": "Investigate",
    "project_name": "Project Name",
    "mp": "MP",
    "district": "District",
    "amount": "Amount",
    "status": "Status",
    "action": "Action",
    "contracts_contractors": "Contracts & Contractors",
    "contractor_name": "Contractor Name",
    "active_contracts": "Active Contracts",
    "total_value": "Total Value",
    "performance": "Performance",
    "showing_contractors": "Showing 5 of 50 active contractors",
    "contractor_registry_link": "Contractor Performance Registry →",
    "showing_projects": "Showing 5 of 28,416 audited projects",
    "filter_by_cat": "Filter by Category / District →",
    "register_vendor": "Register Vendor",
    "category": "Category",
    "products": "Products",
    "showing_vendors": "Showing 5 of 301 registered vendors",
    "material_intel_link": "Material Price Intelligence →",
    "sanctioned": "Sanctioned",
    "utilized": "Utilized",
    "remaining": "Remaining",
    "utilization_rate": "Utilization Rate",
    "allocation_disbursed": "of Allocation Disbursed",
    "monthly_trend": "Monthly Fund Utilization Trend",
    "annual_trend": "Annual Multi-Year Trend",
    "amount_in_cr": "Amount in ₹ Crores",
    "view_financial_analytics": "View Financial Dashboard",
    "official_mospi_audit": "Official MoSPI e-SAKSHI Audited",
    "project_lifecycle": "Project Lifecycle",
    "view_flow": "View Flow",
    "stage_recommendation": "MP Recommendation",
    "stage_sanction": "Sanction by District",
    "stage_tender": "Tender Process",
    "stage_contract": "Contract Award",
    "stage_execution": "Work Execution",
    "stage_completion": "Completion & UC",
    "stage_handover": "Asset Handover",
    "lifecycle_workflow_note": "Standard 7-Tier Statutory Scrutiny & Handover Workflow",
    "pending": "Pending",
    "ai_insights_alerts": "AI Insights & Alerts",
    "new_alerts_badge": "5 New",
    "ai_decision_support": "Decision-Support AI • Continuous Multi-Record Audit",
    "rule_engine": "Rule Engine v2.4",
    "national_gis_title": "National GIS & Satellite Project Radar",
    "national_gis_subtitle": "End-to-End Asset Location, Physical Ground Verification & Anomaly Detection",
    "satellite_mode": "Satellite",
    "vector_mode": "Vector",
    "heatmap_mode": "Risk Heatmap",
    "hierarchy_drilldown": "Hierarchy Drill-Down:",
    "open_village_intel": "Open Village Intelligence",
    "all_states": "All States",
    "sih_banner_desc": "19-stage guided walkthrough: MoSPI Data Ingestion → Digital Map → Rural Intelligence → AI Risk Engine → NetworkX Graph → Human Review → Reports.",
    "launch_demo_btn": "LAUNCH AI INVESTIGATION DEMO",
    "nav_national_pipeline": "National Pipeline",
    "nav_procurement_vendors": "Procurement & Vendors",
    "nav_reports_analytics": "Reports & Analytics",
    "nav_all_projects": "All Projects Directory",
    "nav_digital_twin": "Digital Twin Interactive Map",
    "nav_project_splitting": "Project Splitting Radar",
    "nav_rural_dashboard": "Rural Intelligence Dashboard",
    "nav_village_explorer": "Village Explorer & Map",
    "nav_low_project_villages": "Low-Project Villages (Fewer Works)",
    "nav_data_quality": "Data Quality & LGD Audit",
    "nav_upcoming_opportunities": "Upcoming Opportunities Dashboard",
    "nav_my_interests": "My Interested Projects",
    "nav_express_interest": "Express Interest in Works",
    "nav_tender_portals": "Official Tender Portals & Sources",
    "nav_public_tenders": "Public Works Tenders & NITs",
    "nav_vendor_directory": "Vendor Directory & Marketplace",
    "nav_contractor_registry": "Contractor Performance Registry",
    "nav_supply_chain": "Supply Chain Intelligence",
    "nav_executive_analytics": "Executive Analytics & Reports",
    "nav_fund_mgmt": "Fund Management & Allocation",
    "nav_ai_engine": "AI Risk Engine & Explainability",
    "nav_compliance": "Compliance & Audit Trail"
  },
  "hi": {
    "gov_india": "Government of India",
    "bharat_sarkar": "भारत सरकार",
    "skip_to_content": "मुख्य सामग्री पर जाएं",
    "screen_reader": "स्क्रीन रीडर एक्सेस",
    "sitemap": "साइटमैप",
    "faqs": "अक्सर पूछे जाने वाले प्रश्न",
    "helpdesk": "हेल्पडेस्क",
    "contact_us": "संपर्क करें",
    "mplads_title_1": "संसद सदस्य",
    "mplads_title_2": "स्थानीय क्षेत्र विकास योजना (एमपीलैड्स)",
    "mospi_dept": "सांख्यिकी और कार्यक्रम कार्यान्वयन मंत्रालय",
    "gov_of_india_sub": "भारत सरकार",
    "motto_1": "सबका साथ",
    "motto_2": "सबका विकास",
    "motto_3": "सबका विश्वास",
    "motto_4": "सबका प्रयास",
    "nav_home": "मुख्य पृष्ठ",
    "nav_about": "एमपीलैड्स के बारे में",
    "nav_mps": "सांसद",
    "nav_projects": "परियोजनाएं",
    "nav_tenders": "निविदाएं और अनुबंध",
    "nav_vendors": "विक्रेता",
    "nav_funds": "निधि प्रबंधन",
    "nav_reports": "रिपोर्ट",
    "nav_rural_intelligence": "ग्रामीण बुद्धिमत्ता",
    "nav_contractor_opportunities": "ठेकेदार अवसर",
    "nav_ai_insights": "एआई अंतर्दृष्टि",
    "nav_citizen": "नागरिक कोना",
    "search_placeholder": "परियोजनाएं, ठेकेदार, निविदाएं खोजें...",
    "pm_quote": "“एमपीलैड्स के तहत विकास कार्य ज़मीनी स्तर पर प्रत्येक नागरिक के लिए समान प्रगति, पारदर्शिता और लोकतांत्रिक सशक्तीकरण सुनिश्चित करने चाहिए।”",
    "pm_name": "राहुल गांधी",
    "pm_designation": "नेता प्रतिपक्ष (LoP), लोकसभा",
    "lop_quote": "“एमपीलैड्स के तहत विकास कार्य ज़मीनी स्तर पर प्रत्येक नागरिक के लिए समान प्रगति, पारदर्शिता और लोकतांत्रिक सशक्तीकरण सुनिश्चित करने चाहिए।”",
    "lop_name": "राहुल गांधी",
    "lop_designation": "नेता प्रतिपक्ष (LoP), लोकसभा",
    "peoples_vision": "जन-जन का संकल्प",
    "projects_for_progress": "प्रगति के लिए परियोजनाएं",
    "pillar_transparency": "पारदर्शिता",
    "pillar_accountability": "जवाबदेही",
    "pillar_inclusive": "समावेशी विकास",
    "pillar_lasting_assets": "स्थायी संपत्ति",
    "role_overview": "अवलोकन",
    "role_mp": "सांसद दृश्य",
    "role_district": "जिला प्राधिकरण",
    "role_contractor": "ठेकेदार",
    "role_vendor": "विक्रेता",
    "role_ministry": "मंत्रालय",
    "role_citizen": "नागरिक दृश्य",

    "district_auth_loc": "जिला प्राधिकरण, मुंबई",
    "total_mps": "कुल सांसद",
    "total_projects": "कुल परियोजनाएं",
    "sanctioned_amount": "स्वीकृत राशि",
    "contracts_awarded": "अनुबंधित कार्य",
    "works_completed": "पूर्ण कार्य",
    "in_progress": "प्रगति में",
    "delayed": "विलंबित",
    "high_risk": "उच्च जोखिम",
    "project_map_india": "परियोजना मानचित्र – भारत",
    "fund_utilization": "निधि उपयोग",
    "recent_projects": "हाल की परियोजनाएं",
    "vendor_marketplace": "विक्रेता बाज़ार",
    "all_india": "अखिल भारतीय",
    "view_mps": "सांसद देखें",
    "all_years": "सभी वर्ष",
    "view_projects": "परियोजनाएं देखें",
    "view_financials": "वित्तीय विवरण देखें",
    "view_contracts": "अनुबंध देखें",
    "view_details": "विवरण देखें",
    "completed": "पूर्ण",
    "view_assets": "परिसंपत्तियां देखें",
    "view_delayed": "विलंबित देखें",
    "view_all": "सभी देखें",
    "view": "देखें",
    "investigate": "जांच करें",
    "project_name": "परियोजना का नाम",
    "mp": "सांसद",
    "district": "ज़िला",
    "amount": "राशि",
    "status": "स्थिति",
    "action": "कार्रवाई",
    "contracts_contractors": "अनुबंध और ठेकेदार",
    "contractor_name": "ठेकेदार का नाम",
    "active_contracts": "सक्रिय अनुबंध",
    "total_value": "कुल मूल्य",
    "performance": "प्रदर्शन",
    "showing_contractors": "50 सक्रिय ठेकेदारों में से 5 प्रदर्शित",
    "contractor_registry_link": "ठेकेदार प्रदर्शन पंजी →",
    "showing_projects": "28,416 लेखापरीक्षित परियोजनाओं में से 5 प्रदर्शित",
    "filter_by_cat": "श्रेणी / जिले के अनुसार फ़िल्टर करें →",
    "register_vendor": "विक्रेता पंजीकृत करें",
    "category": "श्रेणी",
    "products": "उत्पाद",
    "showing_vendors": "301 पंजीकृत विक्रेताओं में से 5 प्रदर्शित",
    "material_intel_link": "सामग्री मूल्य विश्लेषण →",
    "sanctioned": "स्वीकृत",
    "utilized": "उपयोग किया गया",
    "remaining": "शेष",
    "utilization_rate": "उपयोग दर",
    "allocation_disbursed": "आवंटन वितरित",
    "monthly_trend": "मासिक निधि उपयोग प्रवृत्ति",
    "annual_trend": "वार्षिक बहु-वर्षीय प्रवृत्ति",
    "amount_in_cr": "राशि ₹ करोड़ में",
    "view_financial_analytics": "वित्तीय डैशबोर्ड देखें",
    "official_mospi_audit": "सांख्यिकी मंत्रालय (e-SAKSHI) द्वारा अधिकृत",
    "project_lifecycle": "परियोजना जीवनचक्र",
    "view_flow": "प्रवाह देखें",
    "stage_recommendation": "सांसद अनुशंसा",
    "stage_sanction": "ज़िला अनुमोदन",
    "stage_tender": "निविदा प्रक्रिया",
    "stage_contract": "अनुबंध आवंटन",
    "stage_execution": "कार्य निष्पादन",
    "stage_completion": "पूर्णता व उपयोग प्रमाणपत्र",
    "stage_handover": "परिसंपत्ति हस्तांतरण",
    "lifecycle_workflow_note": "मानक 7-स्तरीय वैधानिक समीक्षा एवं हस्तांतरण कार्यप्रवाह",
    "pending": "लंबित",
    "ai_insights_alerts": "एआई अंतर्दृष्टि और अलर्ट",
    "new_alerts_badge": "5 नए",
    "ai_decision_support": "निर्णय समर्थन एआई • सतत बहु-अभिलेख लेखापरीक्षा",
    "rule_engine": "नियम इंजन v2.4",
    "national_gis_title": "राष्ट्रीय जीआईएस और उपग्रह परियोजना रडार",
    "national_gis_subtitle": "संपूर्ण परिसंपत्ति स्थान, भौतिक ज़मीनी सत्यापन और विसंगति पहचान",
    "satellite_mode": "उपग्रह",
    "vector_mode": "वेक्टर",
    "heatmap_mode": "जोखिम हीटमैप",
    "hierarchy_drilldown": "पदानुक्रम विवरण:",
    "open_village_intel": "ग्राम बुद्धिमत्ता खोलें",
    "all_states": "सभी राज्य",
    "sih_banner_title": "स्मार्ट इंडिया हैकाथॉन (SIH) 2026 मूल्यांकन मोड",
    "sih_banner_desc": "19-चरणों का निर्देशित पूर्वावलोकन: सांख्यिकी डेटा → डिजिटल मानचित्र → ग्रामीण बुद्धिमत्ता → एआई जोखिम इंजन → मानव समीक्षा → रिपोर्ट।",
    "launch_demo_btn": "एआई जांच डेमो शुरू करें",
    "nav_national_pipeline": "राष्ट्रीय डेटा पाइपलाइन",
    "nav_procurement_vendors": "खरीद और विक्रेता",
    "nav_reports_analytics": "रिपोर्ट और विश्लेषण",
    "nav_all_projects": "सभी परियोजनाएं निर्देशिका",
    "nav_digital_twin": "डिजिटल ट्विन इंटरएक्टिव मानचित्र",
    "nav_project_splitting": "परियोजना विभाजन रडार",
    "nav_rural_dashboard": "ग्रामीण बुद्धिमत्ता डैशबोर्ड",
    "nav_village_explorer": "ग्राम अन्वेषक और मानचित्र",
    "nav_low_project_villages": "कम परियोजना वाले गांव",
    "nav_data_quality": "डेटा गुणवत्ता एवं एलजीडी ऑडिट",
    "nav_upcoming_opportunities": "आगामी अवसर डैशबोर्ड",
    "nav_my_interests": "मेरी रुचि की परियोजनाएं",
    "nav_express_interest": "कार्यों में रुचि व्यक्त करें",
    "nav_tender_portals": "आधिकारिक निविदा पोर्टल",
    "nav_public_tenders": "सार्वजनिक कार्य निविदाएं",
    "nav_vendor_directory": "विक्रेता निर्देशिका और बाज़ार",
    "nav_contractor_registry": "ठेकेदार प्रदर्शन रजिस्ट्री",
    "nav_supply_chain": "आपूर्ति श्रृंखला बुद्धिमत्ता",
    "nav_executive_analytics": "कार्यकारी विश्लेषण एवं रिपोर्ट",
    "nav_fund_mgmt": "निधि प्रबंधन और आवंटन",
    "nav_ai_engine": "एआई जोखिम इंजन",
    "nav_compliance": "अनुपालन एवं ऑडिट ट्रेल"
  },
  "mr": {
    "gov_india": "Government of India",
    "bharat_sarkar": "भारत सरकार",
    "skip_to_content": "मुख्य सामग्रीकडे जा",
    "screen_reader": "स्क्रीन रीडर प्रवेश",
    "sitemap": "साइटमॅप",
    "faqs": "नेहमी विचारले जाणारे प्रश्न",
    "helpdesk": "मदत केंद्र",
    "contact_us": "संपर्क साधा",
    "mplads_title_1": "खासदार",
    "mplads_title_2": "स्थानिक क्षेत्र विकास योजना (MPLADS)",
    "mospi_dept": "सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय",
    "gov_of_india_sub": "भारत सरकार",
    "motto_1": "सबका साथ",
    "motto_2": "सबका विकास",
    "motto_3": "सबका विश्वास",
    "motto_4": "सबका प्रयास",
    "nav_home": "मुख्य पृष्ठ",
    "nav_about": "MPLADS बद्दल",
    "nav_mps": "खासदार",
    "nav_projects": "प्रकल्प",
    "nav_tenders": "निविदा आणि कंत्राटे",
    "nav_vendors": "विक्रेते",
    "nav_funds": "निधी व्यवस्थापन",
    "nav_reports": "अहवाल",
    "nav_rural_intelligence": "ग्रामीण बुद्धिमत्ता",
    "nav_contractor_opportunities": "कंत्राटदार संधी",
    "nav_ai_insights": "AI अंतर्दृष्टी",
    "nav_citizen": "नागरिक विभाग",
    "search_placeholder": "प्रकल्प, कंत्राटदार, निविदा शोधा...",
    "pm_quote": "“MPLADS अंतर्गत विकासकामे तळागाळातील प्रत्येक नागरिकासाठी समान प्रगती, पारदर्शकता आणि लोकशाही सक्षमीकरण सुनिश्चित करणारी असावीत.”",
    "pm_name": "राहुल गांधी",
    "pm_designation": "विरोधी पक्षनेते (LoP), लोकसभा",
    "lop_quote": "“MPLADS अंतर्गत विकासकामे तळागाळातील प्रत्येक नागरिकासाठी समान प्रगती, पारदर्शकता आणि लोकशाही सक्षमीकरण सुनिश्चित करणारी असावीत.”",
    "lop_name": "राहुल गांधी",
    "lop_designation": "विरोधी पक्षनेते (LoP), लोकसभा",
    "peoples_vision": "जनतेचा दृष्टीकोन",
    "projects_for_progress": "प्रगतीसाठी प्रकल्प",
    "pillar_transparency": "पारदर्शकता",
    "pillar_accountability": "जबाबदारी",
    "pillar_inclusive": "समावेशक विकास",
    "pillar_lasting_assets": "शाश्वत मालमत्ता",
    "role_overview": "आढावा",
    "role_mp": "खासदार दृश्य",
    "role_district": "जिल्हा प्राधिकरण",
    "role_contractor": "कंत्राटदार",
    "role_vendor": "विक्रेता",
    "role_ministry": "मंत्रालय",
    "role_citizen": "नागरिक दृश्य",
    "district_auth_loc": "जिल्हा प्राधिकरण, मुंबई",
    "total_mps": "एकूण खासदार",
    "total_projects": "एकूण प्रकल्प",
    "sanctioned_amount": "मंजूर रक्कम",
    "contracts_awarded": "दिलेली कंत्राटे",
    "works_completed": "पूर्ण झालेली कामे",
    "in_progress": "प्रगतीपथावर",
    "delayed": "विलंबित",
    "high_risk": "उच्च जोखीम",
    "project_map_india": "प्रकल्प नकाशा – भारत",
    "fund_utilization": "निधी वापर",
    "recent_projects": "नुकतेच प्रकल्प",
    "vendor_marketplace": "विक्रेता बाजार",
    "all_india": "अखिल भारतीय",
    "view_mps": "खासदार पहा",
    "all_years": "सर्व वर्षे",
    "view_projects": "प्रकल्प पहा",
    "view_financials": "आर्थिक तपशील पहा",
    "view_contracts": "कंत्राटे पहा",
    "view_details": "तपशील पहा",
    "completed": "पूर्ण",
    "view_assets": "मालमत्ता पहा",
    "view_delayed": "विलंबित कामे पहा",
    "view_all": "सर्व पहा",
    "view": "पहा",
    "investigate": "चौकशी करा",
    "project_name": "प्रकल्पाचे नाव",
    "mp": "खासदार",
    "district": "जिल्हा",
    "amount": "रक्कम",
    "status": "स्थिती",
    "action": "कृती",
    "contracts_contractors": "कंत्राटे आणि कंत्राटदार",
    "contractor_name": "कंत्राटदाराचे नाव",
    "active_contracts": "सक्रिय कंत्राटे",
    "total_value": "एकूण मूल्य",
    "performance": "कामगिरी",
    "showing_contractors": "५० पैकी ५ सक्रिय कंत्राटदार दाखवत आहे",
    "contractor_registry_link": "कंत्राटदार कामगिरी नोंदवही →",
    "showing_projects": "२८,४१६ पैकी ५ लेखापरीक्षित प्रकल्प दाखवत आहे",
    "filter_by_cat": "श्रेणी / जिल्ह्यानुसार फिल्टर करा →",
    "register_vendor": "विक्रेता नोंदणी करा",
    "category": "श्रेणी",
    "products": "उत्पादने",
    "showing_vendors": "३०१ पैकी ५ नोंदणीकृत विक्रेते दाखवत आहे",
    "material_intel_link": "साहित्य दर विश्लेषण →",
    "sanctioned": "मंजूर",
    "utilized": "वापरलेले",
    "remaining": "शिल्लक",
    "utilization_rate": "वापर दर",
    "allocation_disbursed": "वाटप वितरित",
    "monthly_trend": "मासिक निधी वापर कल",
    "annual_trend": "वार्षिक बहु-वर्षीय कल",
    "amount_in_cr": "रक्कम ₹ कोटी मध्ये",
    "view_financial_analytics": "आर्थिक डॅशबोर्ड पहा",
    "official_mospi_audit": "सांख्यिकी मंत्रालय (e-SAKSHI) द्वारे अधिकृत",
    "project_lifecycle": "प्रकल्प जीवनचक्र",
    "view_flow": "प्रवाह पहा",
    "stage_recommendation": "खासदार शिफारस",
    "stage_sanction": "जिल्हा मंजुरी",
    "stage_tender": "निविदा प्रक्रिया",
    "stage_contract": "कंत्राट वाटप",
    "stage_execution": "काम सुरू",
    "stage_completion": "पूर्णत्व व उपयोगिता प्रमाणपत्र",
    "stage_handover": "मालमत्ता हस्तांतरण",
    "lifecycle_workflow_note": "मानक ७-स्तरीय वैधानिक छाननी आणि हस्तांतरण कार्यप्रवाह",
    "pending": "प्रलंबित",
    "ai_insights_alerts": "AI अंतर्दृष्टी आणि सूचना",
    "new_alerts_badge": "५ नवीन",
    "ai_decision_support": "निर्णय समर्थन AI • अखंड बहु-अभिलेख लेखापरीक्षण",
    "rule_engine": "नियम इंजिन v2.4",
    "national_gis_title": "राष्ट्रीय GIS आणि उपग्रह प्रकल्प रडार",
    "national_gis_subtitle": "मालमत्ता स्थान, जमिनीवरील पडताळणी आणि त्रुटी ओळख",
    "satellite_mode": "उपग्रह",
    "vector_mode": "व्हेक्टर",
    "heatmap_mode": "जोखीम हीटमॅप",
    "hierarchy_drilldown": "पदानुक्रम माहिती:",
    "open_village_intel": "ग्राम बुद्धिमत्ता उघडा",
    "all_states": "सर्व राज्ये",
    "sih_banner_title": "स्मार्ट इंडिया हॅकाथॉन (SIH) २०२६ मूल्यमापन मोड",
    "sih_banner_desc": "१९-टप्प्यांची मार्गदर्शित सफर: MoSPI डेटा → डिजिटल नकाशा → ग्रामीण बुद्धिमत्ता → AI जोखीम इंजिन → मानवी पुनरावलोकन → अहवाल.",
    "launch_demo_btn": "AI तपासणी डेमो सुरू करा",
    "nav_national_pipeline": "राष्ट्रीय डेटा पाइपलाइन",
    "nav_procurement_vendors": "खरेदी आणि विक्रेते",
    "nav_reports_analytics": "अहवाल आणि विश्लेषण",
    "nav_all_projects": "सर्व प्रकल्प निर्देशिका",
    "nav_digital_twin": "डिजिटल ट्विन संवादी नकाशा",
    "nav_project_splitting": "प्रकल्प विभाजन रडार",
    "nav_rural_dashboard": "ग्रामीण बुद्धिमत्ता डॅशबोर्ड",
    "nav_village_explorer": "ग्राम शोधक आणि नकाशा",
    "nav_low_project_villages": "कमी प्रकल्प असलेली गावे",
    "nav_data_quality": "डेटा गुणवत्ता आणि LGD ऑडिट",
    "nav_upcoming_opportunities": "आगामी संधी डॅशबोर्ड",
    "nav_my_interests": "माझे आवडते प्रकल्प",
    "nav_express_interest": "कामांमध्ये स्वारस्य व्यक्त करा",
    "nav_tender_portals": "अधिकृत निविदा पोर्टल्स",
    "nav_public_tenders": "सार्वजनिक कामे निविदा",
    "nav_vendor_directory": "विक्रेता निर्देशिका आणि बाजार",
    "nav_contractor_registry": "कंत्राटदार कामगिरी नोंदवही",
    "nav_supply_chain": "पुरवठा साखळी बुद्धिमत्ता",
    "nav_executive_analytics": "कार्यकारी विश्लेषण आणि अहवाल",
    "nav_fund_mgmt": "निधी व्यवस्थापन आणि वाटप",
    "nav_ai_engine": "AI जोखीम इंजिन",
    "nav_compliance": "अनुपालन आणि ऑडिट ट्रेल"
  },
  "ta": {
    "gov_india": "Government of India",
    "bharat_sarkar": "இந்திய அரசு",
    "skip_to_content": "முக்கிய உள்ளடக்கத்திற்குச் செல்க",
    "screen_reader": "திரை வாசிப்பான் அணுகல்",
    "sitemap": "தள வரைபடம்",
    "faqs": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "helpdesk": "உதவி மையம்",
    "contact_us": "தொடர்பு கொள்ள",
    "mplads_title_1": "நாடாளுமன்ற உறுப்பினர்கள்",
    "mplads_title_2": "தொகுதி மேம்பாட்டுத் திட்டம் (MPLADS)",
    "mospi_dept": "புள்ளியியல் மற்றும் திட்ட அமலாக்க அமைச்சகம்",
    "gov_of_india_sub": "இந்திய அரசு",
    "motto_1": "அனைவருடனும்",
    "motto_2": "அனைவருக்குமான வளர்ச்சி",
    "motto_3": "அனைவரின் நம்பிக்கை",
    "motto_4": "அனைவரின் முயற்சி",
    "nav_home": "முகப்பு",
    "nav_about": "MPLADS பற்றி",
    "nav_mps": "எம்.பி.க்கள்",
    "nav_projects": "திட்டங்கள்",
    "nav_tenders": "டெண்டர்கள் & ஒப்பந்தங்கள்",
    "nav_vendors": "விற்பனையாளர்கள்",
    "nav_funds": "நிதி மேலாண்மை",
    "nav_reports": "அறிக்கைகள்",
    "nav_rural_intelligence": "கிராமப்புற நுண்ணறிவு",
    "nav_contractor_opportunities": "ஒப்பந்ததாரர் வாய்ப்புகள்",
    "nav_ai_insights": "AI நுண்ணறிவு",
    "nav_citizen": "குடிமக்கள் பகுதி",
    "search_placeholder": "திட்டங்கள், ஒப்பந்ததாரர்கள், டெண்டர்களைத் தேடுங்கள்...",
    "pm_quote": "“MPLADS திட்டத்தின் வளர்ச்சிப் பணிகள் அடித்தட்டு மக்களுக்கான சமத்துவ வளர்ச்சி, வெளிப்படைத்தன்மை மற்றும் ஜனநாயக அதிகாரமளிப்பை உறுதி செய்ய வேண்டும்.”",
    "pm_name": "ராகுல் காந்தி",
    "pm_designation": "எதிர்க்கட்சித் தலைவர் (LoP), மக்களவை",
    "lop_quote": "“MPLADS திட்டத்தின் வளர்ச்சிப் பணிகள் அடித்தட்டு மக்களுக்கான சமத்துவ வளர்ச்சி, வெளிப்படைத்தன்மை மற்றும் ஜனநாயக அதிகாரமளிப்பை உறுதி செய்ய வேண்டும்.”",
    "lop_name": "ராகுல் காந்தி",
    "lop_designation": "எதிர்க்கட்சித் தலைவர் (LoP), மக்களவை",
    "peoples_vision": "மக்களின் தொலைநோக்கு",
    "projects_for_progress": "முன்னேற்றத்திற்கான திட்டங்கள்",
    "pillar_transparency": "வெளிப்படைத்தன்மை",
    "pillar_accountability": "பொறுப்புடைமை",
    "pillar_inclusive": "உள்ளடக்கிய வளர்ச்சி",
    "pillar_lasting_assets": "நிலையான சொத்துக்கள்",
    "role_overview": "கண்ணோட்டம்",
    "role_mp": "எம்.பி பார்வை",
    "role_district": "மாவட்ட நிர்வாகம்",
    "role_contractor": "ஒப்பந்ததாரர்",
    "role_vendor": "விற்பனையாளர்",
    "role_ministry": "அமைச்சகம்",
    "role_citizen": "குடிமக்கள் பார்வை",

    "district_auth_loc": "மாவட்ட அதிகாரம், மும்பை",
    "total_mps": "மொத்த எம்.பி.க்கள்",
    "total_projects": "மொத்த திட்டங்கள்",
    "sanctioned_amount": "ஒப்புதல் அளிக்கப்பட்ட தொகை",
    "contracts_awarded": "வழங்கப்பட்ட ஒப்பந்தங்கள்",
    "works_completed": "முடிக்கப்பட்ட பணிகள்",
    "in_progress": "நடைபெறுகிறது",
    "delayed": "தாமதமானது",
    "high_risk": "அதிக ஆபத்து",
    "project_map_india": "திட்ட வரைபடம் – இந்தியா",
    "fund_utilization": "நிதி பயன்பாடு",
    "recent_projects": "சமீபத்திய திட்டங்கள்",
    "vendor_marketplace": "விற்பனையாளர் சந்தை",
    "all_india": "அகில இந்தியா",
    "view_mps": "எம்.பி.க்களைக் காண்க",
    "all_years": "அனைத்து ஆண்டுகள்",
    "view_projects": "திட்டங்களைக் காண்க",
    "view_financials": "நிதி விவரங்களைக் காண்க",
    "view_contracts": "ஒப்பந்தங்களைக் காண்க",
    "view_details": "விவரங்களைக் காண்க",
    "completed": "முடிந்தது",
    "view_assets": "சொத்துக்களைக் காண்க",
    "view_delayed": "தாமதமானவைகளைக் காண்க",
    "view_all": "அனைத்தையும் காண்க",
    "view": "காண்க",
    "investigate": "விசாரிக்கவும்",
    "project_name": "திட்டத்தின் பெயர்",
    "mp": "எம்.பி",
    "district": "மாவட்டம்",
    "amount": "தொகை",
    "status": "நிலை",
    "action": "செயல்",
    "contracts_contractors": "ஒப்பந்தங்கள் & ஒப்பந்ததாரர்கள்",
    "contractor_name": "ஒப்பந்ததாரர் பெயர்",
    "active_contracts": "செயலில் உள்ள ஒப்பந்தங்கள்",
    "total_value": "மொத்த மதிப்பு",
    "performance": "செயல்திறன்",
    "showing_contractors": "50 ஒப்பந்ததாரர்களில் 5 காண்பிக்கப்படுகிறது",
    "contractor_registry_link": "ஒப்பந்ததாரர் செயல்திறன் பதிவேடு →",
    "showing_projects": "28,416 தணிக்கை செய்யப்பட்ட திட்டங்களில் 5 காண்பிக்கப்படுகிறது",
    "filter_by_cat": "வகை / மாவட்டம் வாரியாக வடிகட்டவும் →",
    "register_vendor": "விற்பனையாளர் பதிவு",
    "category": "வகை",
    "products": "பொருட்கள்",
    "showing_vendors": "301 பதிவு செய்யப்பட்ட விற்பனையாளர்களில் 5 காண்பிக்கப்படுகிறது",
    "material_intel_link": "பொருட்கள் விலை நுண்ணறிவு →",
    "sanctioned": "ஒப்புதல் அளிக்கப்பட்டது",
    "utilized": "பயன்படுத்தப்பட்டது",
    "remaining": "மீதம்",
    "utilization_rate": "பயன்பாட்டு விகிதம்",
    "allocation_disbursed": "ஒதுக்கீடு வழங்கப்பட்டது",
    "monthly_trend": "மாதாந்திர நிதி பயன்பாட்டுப் போக்கு",
    "annual_trend": "ஆண்டு பல ஆண்டுப் போக்கு",
    "amount_in_cr": "தொகை ₹ கோடிகளில்",
    "view_financial_analytics": "நிதி டாஷ்போர்டைக் காண்க",
    "official_mospi_audit": "MoSPI e-SAKSHI அதிகாரப்பூர்வ தணிக்கை",
    "project_lifecycle": "திட்ட வாழ்க்கைச் சுழற்சி",
    "view_flow": "செயல்முறையைக் காண்க",
    "stage_recommendation": "எம்.பி பரிந்துரை",
    "stage_sanction": "மாவட்ட ஒப்புதல்",
    "stage_tender": "டெண்டர் செயல்முறை",
    "stage_contract": "ஒப்பந்தம் வழங்கல்",
    "stage_execution": "பணி நிறைவேற்றம்",
    "stage_completion": "நிறைவு மற்றும் பயன்பாட்டுச் சான்றிதழ்",
    "stage_handover": "சொத்து ஒப்படைப்பு",
    "lifecycle_workflow_note": "நிலையான 7-நிலை சட்டரீதியான சரிபார்ப்பு மற்றும் ஒப்படைப்பு பணிப்பாய்வு",
    "pending": "நிலுவையில்",
    "ai_insights_alerts": "AI நுண்ணறிவு & எச்சரிக்கைகள்",
    "new_alerts_badge": "5 புதியவை",
    "ai_decision_support": "முடிவு ஆதரவு AI • தொடர் பல பதிவு தணிக்கை",
    "rule_engine": "விதி எஞ்சின் v2.4",
    "national_gis_title": "தேசிய GIS & செயற்கைக்கோள் திட்ட ரேடார்",
    "national_gis_subtitle": "சொத்து இருப்பிடம், நேரடி தரை சரிபார்ப்பு மற்றும் முரண்பாடு கண்டறிதல்",
    "satellite_mode": "செயற்கைக்கோள்",
    "vector_mode": "திசையன்",
    "heatmap_mode": "ஆபத்து வெப்ப வரைபடம்",
    "hierarchy_drilldown": "படிநிலை விவரம்:",
    "open_village_intel": "கிராம நுண்ணறிவைத் திறக்கவும்",
    "all_states": "அனைத்து மாநிலங்கள்",
    "sih_banner_title": "Smart India Hackathon (SIH) 2026 மதிப்பீட்டாளர் முறை",
    "sih_banner_desc": "19-படி வழிகாட்டப்பட்ட பயணம்: MoSPI தரவு → டிஜிட்டல் வரைபடம் → கிராமப்புற நுண்ணறிவு → AI ஆபத்து எஞ்சின் → மனித ஆய்வு → அறிக்கைகள்.",
    "launch_demo_btn": "AI விசாரணை டெமோவைத் தொடங்கு",
    "nav_national_pipeline": "தேசிய தரவு குழாய்",
    "nav_procurement_vendors": "கொள்முதல் & விற்பனையாளர்கள்",
    "nav_reports_analytics": "அறிக்கைகள் & பகுப்பாய்வு",
    "nav_all_projects": "அனைத்து திட்டங்களின் அடைவு",
    "nav_digital_twin": "டிஜிட்டல் இரட்டை ஊடாடும் வரைபடம்",
    "nav_project_splitting": "திட்டப் பிரிவு ரேடார்",
    "nav_rural_dashboard": "கிராமப்புற நுண்ணறிவு டாஷ்போர்டு",
    "nav_village_explorer": "கிராம ஆய்வாளர் & வரைபடம்",
    "nav_low_project_villages": "குறைந்த திட்டங்களைக் கொண்ட கிராமங்கள்",
    "nav_data_quality": "தரவு தரம் & LGD தணிக்கை",
    "nav_upcoming_opportunities": "வரவிருக்கும் வாய்ப்புகள் டாஷ்போர்டு",
    "nav_my_interests": "எனது ஆர்வமுள்ள திட்டங்கள்",
    "nav_express_interest": "பணிகளில் ஆர்வம் தெரிவிக்கவும்",
    "nav_tender_portals": "அதிகாரப்பூர்வ டெண்டர் இணையதளங்கள்",
    "nav_public_tenders": "பொதுப்பணி டெண்டர்கள்",
    "nav_vendor_directory": "விற்பனையாளர் அடைவு & சந்தை",
    "nav_contractor_registry": "ஒப்பந்ததாரர் செயல்திறன் பதிவேடு",
    "nav_supply_chain": "விநியோகச் சங்கிலி நுண்ணறிவு",
    "nav_executive_analytics": "நிர்வாக பகுப்பாய்வு & அறிக்கைகள்",
    "nav_fund_mgmt": "நிதி மேலாண்மை & ஒதுக்கீடு",
    "nav_ai_engine": "AI ஆபத்து எஞ்சின்",
    "nav_compliance": "இணக்கம் & தணிக்கை தடம்"
  },
  "te": {
    "gov_india": "Government of India",
    "bharat_sarkar": "భారత ప్రభుత్వం",
    "skip_to_content": "ప్రధాన కంటెంట్‌కు వెళ్లండి",
    "screen_reader": "స్క్రీన్ రీడర్ యాక్సెస్",
    "sitemap": "సైట్‌మ్యాప్",
    "faqs": "తరచుగా అడిగే ప్రశ్నలు",
    "helpdesk": "సహాయ కేంద్రం",
    "contact_us": "మమ్మల్ని సంప్రదించండి",
    "mplads_title_1": "పార్లమెంటు సభ్యులు",
    "mplads_title_2": "స్థానిక ప్రాంత అభివృద్ధి పథకం (MPLADS)",
    "mospi_dept": "గణాంకాలు మరియు కార్యక్రమ అమలు మంత్రిత్వ శాఖ",
    "gov_of_india_sub": "భారత ప్రభుత్వం",
    "motto_1": "సబ్‌కా సాథ్",
    "motto_2": "సబ్‌కా వికాస్",
    "motto_3": "సబ్‌కా విశ్వాస్",
    "motto_4": "సబ్‌కా ప్రయాస్",
    "nav_home": "హోమ్",
    "nav_about": "MPLADS గురించి",
    "nav_mps": "ఎంపీలు",
    "nav_projects": "ప్రాజెక్ట్‌లు",
    "nav_tenders": "టెండర్లు & ఒప్పందాలు",
    "nav_vendors": "విక్రేతలు",
    "nav_funds": "నిధుల నిర్వహణ",
    "nav_reports": "నివేదికలు",
    "nav_rural_intelligence": "గ్రామీణ ఇంటెలిజెన్స్",
    "nav_contractor_opportunities": "కాంట్రాక్టర్ అవకాశాలు",
    "nav_ai_insights": "AI ఇన్‌సైట్‌లు",
    "nav_citizen": "పౌరుల వేదిక",
    "search_placeholder": "ప్రాజెక్ట్‌లు, కాంట్రాక్టర్లు, టెండర్లను శోధించండి...",
    "pm_quote": "“MPLADS కింద అభివృద్ధి పనులు అట్టడుగు స్థాయి పౌరులందరికీ సమాన ప్రగతి, పారదర్శకత మరియు ప్రజాస్వామ్య సాధికారతను అందించాలి.”",
    "pm_name": "రాహుల్ గాంధీ",
    "pm_designation": "ప్రతిపక్ష నాయకుడు (LoP), లోక్‌సభ",
    "lop_quote": "“MPLADS కింద అభివృద్ధి పనులు అట్టడుగు స్థాయి పౌరులందరికీ సమాన ప్రగతి, పారదర్శకత మరియు ప్రజాస్వామ్య సాధికారతను అందించాలి.”",
    "lop_name": "రాహుల్ గాంధీ",
    "lop_designation": "ప్రతిపక్ష నాయకుడు (LoP), లోక్‌సభ",
    "peoples_vision": "ప్రజల దార్శనికత",
    "projects_for_progress": "పురోగతి కోసం ప్రాజెక్టులు",
    "pillar_transparency": "పారదర్శకత",
    "pillar_accountability": "బాధ్యతాయుతత్వం",
    "pillar_inclusive": "సమ్మిళిత అభివృద్ధి",
    "pillar_lasting_assets": "శాశ్వత ఆస్తులు",
    "role_overview": "సమీక్ష",
    "role_mp": "ఎంపీ వీక్షణ",
    "role_district": "జిల్లా అధికారం",
    "role_contractor": "కాంట్రాక్టర్",
    "role_vendor": "విక్రేత",
    "role_ministry": "మంత్రిత్వ శాఖ",
    "role_citizen": "పౌరుల వీక్షణ",
    "district_auth_loc": "జిల్లా అధికారం, ముంబై",
    "total_mps": "మొత్తం ఎంపీలు",
    "total_projects": "మొత్తం ప్రాజెక్ట్‌లు",
    "sanctioned_amount": "మంజూరైన మొత్తం",
    "contracts_awarded": "కేటాయించిన కాంట్రాక్టులు",
    "works_completed": "పూర్తయిన పనులు",
    "in_progress": "పురోగతిలో ఉంది",
    "delayed": "ఆలస్యమైంది",
    "high_risk": "అధిక ప్రమాదం",
    "project_map_india": "ప్రాజెక్ట్ మ్యాప్ – భారతదేశం",
    "fund_utilization": "నిధుల వినియోగం",
    "recent_projects": "ఇటీవలి ప్రాజెక్ట్‌లు",
    "vendor_marketplace": "విక్రేతల మార్కెట్",
    "all_india": "భారతదేశం అంతటా",
    "view_mps": "ఎంపీలను చూడండి",
    "all_years": "అన్ని సంవత్సరాలు",
    "view_projects": "ప్రాజెక్ట్‌లను చూడండి",
    "view_financials": "ఆర్థిక వివరాలు చూడండి",
    "view_contracts": "కాంట్రాక్టులను చూడండి",
    "view_details": "వివరాలను చూడండి",
    "completed": "పూర్తయింది",
    "view_assets": "ఆస్తులను చూడండి",
    "view_delayed": "ఆలస్యమైనవి చూడండి",
    "view_all": "అన్నీ చూడండి",
    "view": "చూడండి",
    "investigate": "దర్యాప్తు చేయండి",
    "project_name": "ప్రాజెక్ట్ పేరు",
    "mp": "ఎంపీ",
    "district": "జిల్లా",
    "amount": "మొత్తం",
    "status": "స్థితి",
    "action": "చర్య",
    "contracts_contractors": "కాంట్రాక్టులు & కాంట్రాక్టర్లు",
    "contractor_name": "కాంట్రాక్టర్ పేరు",
    "active_contracts": "క్రియాశీల కాంట్రాక్టులు",
    "total_value": "మొత్తం విలువ",
    "performance": "పనితీరు",
    "showing_contractors": "50 క్రియాశీల కాంట్రాక్టర్లలో 5 చూపిస్తోంది",
    "contractor_registry_link": "కాంట్రాక్టర్ పనితీరు రిజిస్ట్రీ →",
    "showing_projects": "28,416 ఆడిట్ చేయబడిన ప్రాజెక్ట్‌లలో 5 చూపిస్తోంది",
    "filter_by_cat": "వర్గం / జిల్లా వారీగా ఫిల్టర్ చేయండి →",
    "register_vendor": "విక్రేతను నమోదు చేయండి",
    "category": "వర్గం",
    "products": "ఉత్పత్తులు",
    "showing_vendors": "301 నమోదు చేసుకున్న విక్రేతలలో 5 చూపిస్తోంది",
    "material_intel_link": "మెటీరియల్ ధర ఇంటెలిజెన్స్ →",
    "sanctioned": "మంజూరైనది",
    "utilized": "వినియోగించినది",
    "remaining": "మిగిలినది",
    "utilization_rate": "వినియోగ రేటు",
    "allocation_disbursed": "కేటాయింపు పంపిణీ చేయబడింది",
    "monthly_trend": "నెలవారీ నిధుల వినియోగ ధోరణి",
    "annual_trend": "వార్షిక బహుళ సంవత్సరాల ధోరణి",
    "amount_in_cr": "మొత్తం ₹ కోట్లలలో",
    "view_financial_analytics": "ఆర్థిక డాష్‌బోర్డ్ చూడండి",
    "official_mospi_audit": "MoSPI e-SAKSHI అధికారిక ఆడిట్",
    "project_lifecycle": "ప్రాజెక్ట్ జీవిత చక్రం",
    "view_flow": "ప్రవాహాన్ని చూడండి",
    "stage_recommendation": "ఎంపీ సిఫార్సు",
    "stage_sanction": "జిల్లా మంజూరు",
    "stage_tender": "టెండర్ ప్రక్రియ",
    "stage_contract": "కాంట్రాక్ట్ అవార్డు",
    "stage_execution": "పని అమలు",
    "stage_completion": "పూర్తి & వినియోగ ధృవీకరణ",
    "stage_handover": "ఆస్తి అప్పగింత",
    "lifecycle_workflow_note": "ప్రామాణిక 7-శ్రేణి చట్టబద్ధమైన పరిశీలన మరియు అప్పగింత వర్క్‌ఫ్లో",
    "pending": "పెండింగ్‌లో ఉంది",
    "ai_insights_alerts": "AI అంతర్దృష్టులు & హెచ్చరికలు",
    "new_alerts_badge": "5 కొత్తవి",
    "ai_decision_support": "నిర్ణయ మద్దతు AI • నిరంతర బహుళ-రికార్డ్ ఆడిట్",
    "rule_engine": "రూల్ ఇంజిన్ v2.4",
    "national_gis_title": "జాతీయ GIS & ఉపగ్రహ ప్రాజెక్ట్ రాడార్",
    "national_gis_subtitle": "ఆస్తి స్థానం, ప్రత్యక్ష గ్రౌండ్ ధృవీకరణ & వ్యత్యాస గుర్తింపు",
    "satellite_mode": "ఉపగ్రహం",
    "vector_mode": "వెక్టర్",
    "heatmap_mode": "ప్రమాద హీట్‌మ్యాప్",
    "hierarchy_drilldown": "క్రమానుగత వివరాలు:",
    "open_village_intel": "గ్రామ ఇంటెలిజెన్స్ తెరవండి",
    "all_states": "అన్ని రాష్ట్రాలు",
    "sih_banner_title": "Smart India Hackathon (SIH) 2026 మూల్యాంకన మోడ్",
    "sih_banner_desc": "19-దశల గైడెడ్ ప్రయాణం: MoSPI డేటా → డిజిటల్ మ్యాప్ → గ్రామీణ ఇంటెలిజెన్స్ → AI రిస్క్ ఇంజిన్ → మానవ సమీక్ష → నివేదికలు.",
    "launch_demo_btn": "AI పరిశోధన డెమోను ప్రారంభించండి",
    "nav_national_pipeline": "జాతీయ డేటా పైప్‌లైన్",
    "nav_procurement_vendors": "సేకరణ & విక్రేతలు",
    "nav_reports_analytics": "నివేదికలు & విశ్లేషణలు",
    "nav_all_projects": "అన్ని ప్రాజెక్ట్‌ల డైరెక్టరీ",
    "nav_digital_twin": "డిజిటల్ ట్విన్ ఇంటరాక్టివ్ మ్యాప్",
    "nav_project_splitting": "ప్రాజెక్ట్ విభజన రాడార్",
    "nav_rural_dashboard": "గ్రామీణ ఇంటెలిజెన్స్ డాష్‌బోర్డ్",
    "nav_village_explorer": "గ్రామ అన్వేషకుడు & మ్యాప్",
    "nav_low_project_villages": "తక్కువ ప్రాజెక్టులు ఉన్న గ్రామాలు",
    "nav_data_quality": "డేటా నాణ్యత & LGD ఆడిట్",
    "nav_upcoming_opportunities": "రాబోయే అవకాశాల డాష్‌బోర్డ్",
    "nav_my_interests": "నా ఆసక్తిగల ప్రాజెక్ట్‌లు",
    "nav_express_interest": "పనులపై ఆసక్తిని వ్యక్తపరచండి",
    "nav_tender_portals": "అధికారిక టెండర్ పోర్టల్‌లు",
    "nav_public_tenders": "ప్రజా పనుల టెండర్లు",
    "nav_vendor_directory": "విక్రేతల డైరెక్టరీ & మార్కెట్",
    "nav_contractor_registry": "కాంట్రాక్టర్ పనితీరు రిజిస్ట్రీ",
    "nav_supply_chain": "సరఫరా గొలుసు ఇంటెలిజెన్స్",
    "nav_executive_analytics": "ఎగ్జిక్యూటివ్ అనలిటిక్స్ & నివేదికలు",
    "nav_fund_mgmt": "నిధుల నిర్వహణ & కేటాయింపు",
    "nav_ai_engine": "AI రిస్క్ ఇంజిన్",
    "nav_compliance": "వర్తింపు & ఆడిట్ ట్రెయిల్"
  },
  "bn": {
    "gov_india": "Government of India",
    "bharat_sarkar": "ভারত সরকার",
    "skip_to_content": "মূল বিষয়বস্তুতে যান",
    "screen_reader": "স্ক্রিন রিডার অ্যাক্সেস",
    "sitemap": "সাইটম্যাপ",
    "faqs": "সাধারণ প্রশ্নাবলী",
    "helpdesk": "হেল্পডেস্ক",
    "contact_us": "যোগাযোগ করুন",
    "mplads_title_1": "সংসদ সদস্য",
    "mplads_title_2": "স্থানীয় এলাকা উন্নয়ন প্রকল্প (MPLADS)",
    "mospi_dept": "পরিসংখ্যান ও কর্মসূচি বাস্তবায়ন মন্ত্রণালয়",
    "gov_of_india_sub": "ভারত সরকার",
    "motto_1": "সবকা সাথ",
    "motto_2": "সবকা বিকাশ",
    "motto_3": "সবকা বিশ্বাস",
    "motto_4": "সবকা প্রয়াস",
    "nav_home": "হোম",
    "nav_about": "MPLADS সম্পর্কে",
    "nav_mps": "সাংসদগণ",
    "nav_projects": "প্রকল্পসমূহ",
    "nav_tenders": "টেন্ডার ও চুক্তি",
    "nav_vendors": "বিক্রেতা",
    "nav_funds": "তহবিল ব্যবস্থাপনা",
    "nav_reports": "প্রতিবেদন",
    "nav_rural_intelligence": "গ্রামীণ বুদ্ধিমত্তা",
    "nav_contractor_opportunities": "ঠিকাদার সুযোগ",
    "nav_ai_insights": "AI অন্তর্দৃষ্টি",
    "nav_citizen": "নাগরিক কর্নার",
    "search_placeholder": "প্রকল্প, ঠিকাদার, টেন্ডার অনুসন্ধান করুন...",
    "pm_quote": "“MPLADS-এর অধীনে উন্নয়নমূলক কাজ তৃণমূল স্তরে প্রতিটি नागरिकের জন্য সমতাভিত্তিক প্রগতি, স্বচ্ছতা ও গণতান্ত্রিক ক্ষমতায়ন নিশ্চিত করা উচিত।”",
    "pm_name": "রাহুল গান্ধী",
    "pm_designation": "বিরোধী দলনেতা (LoP), লোকসভা",
    "lop_quote": "“MPLADS-এর অধীনে উন্নয়নমূলক কাজ তৃণমূল স্তরে প্রতিটি নাগরিকের জন্য সমতাভিত্তিক প্রগতি, স্বচ্ছতা ও গণতান্ত্রিক ক্ষমতায়ন নিশ্চিত করা উচিত।”",
    "lop_name": "রাহুল গান্ধী",
    "lop_designation": "বিরোধী দলনেতা (LoP), লোকসভা",
    "peoples_vision": "জনগণের দৃষ্টিভঙ্গি",
    "projects_for_progress": "অগ্রগতির জন্য প্রকল্প",
    "pillar_transparency": "স্বচ্ছতা",
    "pillar_accountability": "দায়বদ্ধতা",
    "pillar_inclusive": "অন্তর্ভুক্তিমূলক উন্নয়ন",
    "pillar_lasting_assets": "স্থায়ী সম্পদ",
    "role_overview": "সারসংক্ষেপ",
    "role_mp": "সাংসদ দৃশ্য",
    "role_district": "জেলা কর্তৃপক্ষ",
    "role_contractor": "ঠিকাদার",
    "role_vendor": "বিক্রেতা",
    "role_ministry": "মন্ত্রণালয়",
    "role_citizen": "নাগরিক দৃশ্য",
    "district_auth_loc": "জেলা কর্তৃপক্ষ, মুম্বাই",
    "total_mps": "মোট সাংসদ",
    "total_projects": "মোট প্রকল্প",
    "sanctioned_amount": "অনুমোদিত পরিমাণ",
    "contracts_awarded": "প্রদত্ত চুক্তি",
    "works_completed": "সম্পন্ন কাজ",
    "in_progress": "চলমান",
    "delayed": "বিলম্বিত",
    "high_risk": "উচ্চ ঝুঁকি",
    "project_map_india": "প্রকল্প মানচিত্র – ভারত",
    "fund_utilization": "তহবিল ব্যবহার",
    "recent_projects": "সাম্প্রতিক প্রকল্প",
    "vendor_marketplace": "বিক্রেতা বাজার",
    "all_india": "সারা ভারত",
    "view_mps": "সাংসদদের দেখুন",
    "all_years": "সকল বছর",
    "view_projects": "প্রকল্প দেখুন",
    "view_financials": "আর্থিক বিবরণ দেখুন",
    "view_contracts": "চুক্তি দেখুন",
    "view_details": "বিস্তারিত দেখুন",
    "completed": "সম্পন্ন",
    "view_assets": "সম্পদ দেখুন",
    "view_delayed": "বিলম্বিত কাজ দেখুন",
    "view_all": "সব দেখুন",
    "view": "দেখুন",
    "investigate": "তদন্ত করুন",
    "project_name": "প্রকল্পের নাম",
    "mp": "সাংসদ",
    "district": "জেলা",
    "amount": "পরিমাণ",
    "status": "অবস্থা",
    "action": "পদক্ষেপ",
    "contracts_contractors": "চুক্তি এবং ঠিকাদার",
    "contractor_name": "ঠিকাদারের নাম",
    "active_contracts": "সক্রিয় চুক্তি",
    "total_value": "মোট মূল্য",
    "performance": "কর্মক্ষমতা",
    "showing_contractors": "৫০ জন সক্রিয় ঠিকাদারের মধ্যে ৫ জন প্রদর্শিত হচ্ছে",
    "contractor_registry_link": "ঠিকাদার কর্মক্ষমতা রেজিস্ট্রি →",
    "showing_projects": "২৮,৪১৬টি নিরীক্ষিত প্রকল্পের মধ্যে ৫টি প্রদর্শিত হচ্ছে",
    "filter_by_cat": "বিভাগ / জেলা অনুযায়ী ফিল্টার করুন →",
    "register_vendor": "বিক্রেতা নিবন্ধন করুন",
    "category": "বিভাগ",
    "products": "পণ্য",
    "showing_vendors": "৩০১ জন নিবন্ধিত বিক্রেতার মধ্যে ৫ জন প্রদর্শিত হচ্ছে",
    "material_intel_link": "উপাদান মূল্য বিশ্লেষণ →",
    "sanctioned": "অনুমোদিত",
    "utilized": "ব্যবহৃত",
    "remaining": "অবশিষ্ট",
    "utilization_rate": "ব্যবহারের হার",
    "allocation_disbursed": "বরাদ্দ বিতরণ করা হয়েছে",
    "monthly_trend": "মাসিক তহবিল ব্যবহারের প্রবণতা",
    "annual_trend": "বার্ষিক বহু-বছরের প্রবণতা",
    "amount_in_cr": "পরিমাণ ₹ কোটিতে",
    "view_financial_analytics": "আর্থিক ড্যাশবোর্ড দেখুন",
    "official_mospi_audit": "MoSPI e-SAKSHI অফিসিয়াল অডিট",
    "project_lifecycle": "প্রকল্পের জীবনচক্র",
    "view_flow": "প্রবাহ দেখুন",
    "stage_recommendation": "সাংসদের সুপারিশ",
    "stage_sanction": "জেলা অনুমোদন",
    "stage_tender": "টেন্ডার প্রক্রিয়া",
    "stage_contract": "চুক্তি প্রদান",
    "stage_execution": "কাজ সম্পাদন",
    "stage_completion": "সমাপ্তি ও ব্যবহারের শংসাপত্র",
    "stage_handover": "সম্পদ হস্তান্তর",
    "lifecycle_workflow_note": "মানক ৭-স্তরীয় সংবিধিবদ্ধ যাচাইকরণ ও হস্তান্তর কর্মপ্রবাহ",
    "pending": "মুলতুবি",
    "ai_insights_alerts": "AI অন্তর্দৃষ্টি ও সতর্কতা",
    "new_alerts_badge": "৫টি নতুন",
    "ai_decision_support": "সিদ্ধান্ত সমর্থন AI • ক্রমাগত বহু-নথি নিরীক্ষা",
    "rule_engine": "নিয়ম ইঞ্জিন v2.4",
    "national_gis_title": "জাতীয় GIS এবং উপগ্রহ প্রকল্প রাডার",
    "national_gis_subtitle": "সম্পদ অবস্থান, সরাসরি স্থল যাচাইকরণ এবং অসঙ্গতি সনাক্তকরণ",
    "satellite_mode": "উপগ্রহ",
    "vector_mode": "ভেক্টর",
    "heatmap_mode": "ঝুঁকি হিটম্যাপ",
    "hierarchy_drilldown": "শ্রেণীবিন্যাস বিবরণ:",
    "open_village_intel": "গ্রামের বুদ্ধিমত্তা খুলুন",
    "all_states": "সমস্ত রাজ্য",
    "sih_banner_title": "Smart India Hackathon (SIH) 2026 মূল্যায়ন মোড",
    "sih_banner_desc": "১৯-পর্যায়ের নির্দেশিত পথ: MoSPI ডেটা → ডিজিটাল মানচিত্র → গ্রামীণ বুদ্ধিমত্তা → AI ঝুঁকি ইঞ্জিন → মানবিক পর্যালোচনা → প্রতিবেদন।",
    "launch_demo_btn": "AI তদন্ত ডেমো চালু করুন",
    "nav_national_pipeline": "জাতীয় ডেটা পাইপলাইন",
    "nav_procurement_vendors": "সংগ্রহ ও বিক্রেতা",
    "nav_reports_analytics": "প্রতিবেদন ও বিশ্লেষণ",
    "nav_all_projects": "সমস্ত প্রকল্প ডিরেক্টরি",
    "nav_digital_twin": "ডিজিটাল টুইন ইন্টারেক্টিভ মানচিত্র",
    "nav_project_splitting": "প্রকল্প বিভাজন রাডার",
    "nav_rural_dashboard": "গ্রামীণ বুদ্ধিমত্তা ড্যাশবোর্ড",
    "nav_village_explorer": "গ্রাম এক্সপ্লোরার ও মানচিত্র",
    "nav_low_project_villages": "কম প্রকল্পযুক্ত গ্রাম",
    "nav_data_quality": "ডেটা গুণমান ও LGD অডিট",
    "nav_upcoming_opportunities": "আসন্ন সুযোগ ড্যাশবোর্ড",
    "nav_my_interests": "আমার আগ্রহের প্রকল্প",
    "nav_express_interest": "কাজে আগ্রহ প্রকাশ করুন",
    "nav_tender_portals": "অফিসিয়াল টেন্ডার পোর্টাল",
    "nav_public_tenders": "গণপূর্ত টেন্ডার",
    "nav_vendor_directory": "বিক্রেতা ডিরেক্টরি ও মার্কেটপ্লেস",
    "nav_contractor_registry": "ঠিকাদার কর্মক্ষমতা রেজিস্ট্রি",
    "nav_supply_chain": "সরবরাহ চেইন বুদ্ধিমত্তা",
    "nav_executive_analytics": "নির্বাহী বিশ্লেষণ ও প্রতিবেদন",
    "nav_fund_mgmt": "তহবিল ব্যবস্থাপনা ও বরাদ্দ",
    "nav_ai_engine": "AI ঝুঁকি ইঞ্জিন",
    "nav_compliance": "সম্মতি ও অডিট ট্রেইল"
  },
  "gu": {
    "gov_india": "Government of India",
    "bharat_sarkar": "ભારત સરકાર",
    "skip_to_content": "મુખ્ય સામગ્રી પર જાઓ",
    "screen_reader": "સ્ક્રીન રીડર ઍક્સેસ",
    "sitemap": "સાઇટમેપ",
    "faqs": "વારંવાર પૂછાતા પ્રશ્નો",
    "helpdesk": "હેલ્પડેસ્ક",
    "contact_us": "સંપર્ક કરો",
    "mplads_title_1": "સંસદ સભ્ય",
    "mplads_title_2": "સ્થાનિક વિસ્તાર વિકાસ યોજના (MPLADS)",
    "mospi_dept": "આંકડા અને કાર્યક્રમ અમલીકરણ મંત્રાલય",
    "gov_of_india_sub": "ભારત સરકાર",
    "motto_1": "સબકા સાથ",
    "motto_2": "સબકા વિકાસ",
    "motto_3": "સબકા વિશ્વાસ",
    "motto_4": "સબકા પ્રયાસ",
    "nav_home": "હોમ",
    "nav_about": "MPLADS વિશે",
    "nav_mps": "સાંસદો",
    "nav_projects": "પ્રોજેક્ટ્સ",
    "nav_tenders": "ટેન્ડર અને કરારો",
    "nav_vendors": "વિક્રેતાઓ",
    "nav_funds": "ફંડ મેનેજમેન્ટ",
    "nav_reports": "અહેવાલો",
    "nav_rural_intelligence": "ગ્રામીણ બુદ્ધિપ્રતિભા",
    "nav_contractor_opportunities": "કોન્ટ્રાક્ટર તકો",
    "nav_ai_insights": "AI ઇનસાઇટ્સ",
    "nav_citizen": "નાગરિક કોર્નર",
    "search_placeholder": "પ્રોજેક્ટ્સ, કોન્ટ્રાક્ટરો, ટેન્ડરો શોધો...",
    "pm_quote": "“MPLADS હેઠળ વિકાસ કાર્યો છેવાડાના દરેક નાગરિક માટે સમાન પ્રગતિ, પારદર્શિતા અને લોકશાહી સશક્તિકરણ સુનિશ્ચિત કરવા જોઈએ.”",
    "pm_name": "રાહુલ ગાંધી",
    "pm_designation": "વિરોધ પક્ષના નેતા (LoP), લોકસભા",
    "lop_quote": "“MPLADS હેઠળ વિકાસ કાર્યો છેવાડાના દરેક નાગરિક માટે સમાન પ્રગતિ, પારદર્શિતા અને લોકશાહી સશક્તિકરણ સુનિશ્ચિત કરવા જોઈએ.”",
    "lop_name": "રાહુલ ગાંધી",
    "lop_designation": "વિરોધ પક્ષના નેતા (LoP), લોકસભા",
    "peoples_vision": "જનતાનો સંકલ્પ",
    "projects_for_progress": "પ્રગતિ માટે પ્રોજેક્ટ્સ",
    "pillar_transparency": "પારદર્શિતા",
    "pillar_accountability": "જવાબદારી",
    "pillar_inclusive": "સમાવેશી વિકાસ",
    "pillar_lasting_assets": "કાયમી સંપત્તિ",
    "role_overview": "ઝાંખી",
    "role_mp": "સાંસદ દૃશ્ય",
    "role_district": "જિલ્લા સત્તામંડળ",
    "role_contractor": "કોન્ટ્રાક્ટર",
    "role_vendor": "વિક્રેતા",
    "role_ministry": "મંત્રાલય",
    "role_citizen": "નાગરિક દૃશ્ય",
    "district_auth_loc": "જિલ્લા સત્તામંડળ, મુંબઈ",
    "total_mps": "કુલ સાંસદો",
    "total_projects": "કુલ પ્રોજેક્ટ્સ",
    "sanctioned_amount": "મંજૂર રકમ",
    "contracts_awarded": "આપેલા કરારો",
    "works_completed": "પૂર્ણ થયેલા કામો",
    "in_progress": "ચાલુ છે",
    "delayed": "વિલંબિત",
    "high_risk": "ઉચ્ચ જોખમ",
    "project_map_india": "પ્રોજેક્ટ નકશો – ભારત",
    "fund_utilization": "ફંડ ઉપયોગ",
    "recent_projects": "તાજેતરના પ્રોજેક્ટ્સ",
    "vendor_marketplace": "વિક્રેતા બજાર",
    "all_india": "સમગ્ર ભારત",
    "view_mps": "સાંસદો જુઓ",
    "all_years": "બધા વર્ષો",
    "view_projects": "પ્રોજેક્ટ્સ જુઓ",
    "view_financials": "નાણાકીય વિગતો જુઓ",
    "view_contracts": "કરારો જુઓ",
    "view_details": "વિગતો જુઓ",
    "completed": "પૂર્ણ થયેલ",
    "view_assets": "સંપત્તિ જુઓ",
    "view_delayed": "વિલંબિત જુઓ",
    "view_all": "બધા જુઓ",
    "view": "જુઓ",
    "investigate": "તપાસ કરો",
    "project_name": "પ્રોજેક્ટનું નામ",
    "mp": "સાંસદ",
    "district": "જિલ્લો",
    "amount": "રકમ",
    "status": "સ્થિતિ",
    "action": "પગલાં",
    "contracts_contractors": "કરારો અને કોન્ટ્રાક્ટરો",
    "contractor_name": "કોન્ટ્રાક્ટરનું નામ",
    "active_contracts": "સક્રિય કરારો",
    "total_value": "કુલ મૂલ્ય",
    "performance": "કામગીરી",
    "showing_contractors": "50 સક્રિય કોન્ટ્રાક્ટરોમાંથી 5 દર્શાવે છે",
    "contractor_registry_link": "કોન્ટ્રાક્ટર કામગીરી રજિસ્ટ્રી →",
    "showing_projects": "28,416 ઓડિટ કરેલા પ્રોજેક્ટ્સમાંથી 5 દર્શાવે છે",
    "filter_by_cat": "કેટેગરી / જિલ્લા દ્વારા ફિલ્ટર કરો →",
    "register_vendor": "વિક્રેતા નોંધણી",
    "category": "કેટેગરી",
    "products": "ઉત્પાદનો",
    "showing_vendors": "301 નોંધાયેલા વિક્રેતાઓમાંથી 5 દર્શાવે છે",
    "material_intel_link": "સામગ્રી કિંમત વિશ્લેષણ →",
    "sanctioned": "મંજૂર",
    "utilized": "વપરાયેલ",
    "remaining": "બાકી",
    "utilization_rate": "ઉપયોગ દર",
    "allocation_disbursed": "ફાળવણી વિતરણ",
    "monthly_trend": "માસિક ફંડ ઉપયોગ વલણ",
    "annual_trend": "વાર્ષિક બહુ-વર્ષીય વલણ",
    "amount_in_cr": "રકમ ₹ કરોડમાં",
    "view_financial_analytics": "નાણાકીય ડેશબોર્ડ જુઓ",
    "official_mospi_audit": "સત્તાવાર MoSPI e-SAKSHI ઓડિટ",
    "project_lifecycle": "પ્રોજેક્ટ જીવનચક્ર",
    "view_flow": "પ્રવાહ જુઓ",
    "stage_recommendation": "સાંસદ ભલામણ",
    "stage_sanction": "જિલ્લા મંજૂરી",
    "stage_tender": "ટેન્ડર પ્રક્રિયા",
    "stage_contract": "કરાર ફાળવણી",
    "stage_execution": "કામગીરી અમલીકરણ",
    "stage_completion": "પૂર્ણતા અને ઉપયોગિતા પ્રમાણપત્ર",
    "stage_handover": "સંપત્તિ સોંપણી",
    "lifecycle_workflow_note": "માનક 7-સ્તરીય કાનૂની ચકાસણી અને સોંપણી વર્કફ્લો",
    "pending": "બાકી",
    "ai_insights_alerts": "AI ઇનસાઇટ્સ અને ચેતવણીઓ",
    "new_alerts_badge": "5 નવી",
    "ai_decision_support": "નિર્ણય સપોર્ટ AI • સતત બહુ-રેકોર્ડ ઓડિટ",
    "rule_engine": "નિયમ એન્જિન v2.4",
    "national_gis_title": "રાષ્ટ્રીય GIS અને સેટેલાઇટ પ્રોજેક્ટ રડાર",
    "national_gis_subtitle": "સંપત્તિ સ્થાન, પ્રત્યક્ષ જમીન ચકાસણી અને વિસંગતતા શોધ",
    "satellite_mode": "સેટેલાઇટ",
    "vector_mode": "વેક્ટર",
    "heatmap_mode": "જોખમ હીટમેપ",
    "hierarchy_drilldown": "શ્રેણીબદ્ધ વિગતો:",
    "open_village_intel": "ગ્રામીણ બુદ્ધિપ્રતિભા ખોલો",
    "all_states": "બધા રાજ્યો",
    "sih_banner_title": "Smart India Hackathon (SIH) 2026 મૂલ્યાંકનકર્તા મોડ",
    "sih_banner_desc": "19-તબક્કાની માર્ગદર્શિત મુસાફરી: MoSPI ડેટા → ડિજિટલ નકશો → ગ્રામીણ બુદ્ધિપ્રતિભા → AI જોખમ એન્જિન → માનવીય સમીક્ષા → અહેવાલો.",
    "launch_demo_btn": "AI તપાસ ડેમો શરૂ કરો",
    "nav_national_pipeline": "રાષ્ટ્રીય ડેટા પાઇપલાઇન",
    "nav_procurement_vendors": "ખરીદી અને વિક્રેતાઓ",
    "nav_reports_analytics": "અહેવાલો અને વિશ્લેષણ",
    "nav_all_projects": "બધા પ્રોજેક્ટ્સ ડિરેક્ટરી",
    "nav_digital_twin": "ડિજિટલ ટ્વીન ઇન્ટરેક્ટિવ નકશો",
    "nav_project_splitting": "પ્રોજેક્ટ વિભાજન રડાર",
    "nav_rural_dashboard": "ગ્રામીણ બુદ્ધિપ્રતિભા ડેશબોર્ડ",
    "nav_village_explorer": "ગામ સંશોધક અને નકશો",
    "nav_low_project_villages": "ઓછા પ્રોજેક્ટ્સ ધરાવતા ગામો",
    "nav_data_quality": "ડેટા ગુણવત્તા અને LGD ઓડિટ",
    "nav_upcoming_opportunities": "આગામી તકો ડેશબોર્ડ",
    "nav_my_interests": "મારા રસ ધરાવતા પ્રોજેક્ટ્સ",
    "nav_express_interest": "કામોમાં રસ દર્શાવો",
    "nav_tender_portals": "સત્તાવાર ટેન્ડર પોર્ટલ",
    "nav_public_tenders": "જાહેર બાંધકામ ટેન્ડરો",
    "nav_vendor_directory": "વિક્રેતા ડિરેક્ટરી અને બજાર",
    "nav_contractor_registry": "કોન્ટ્રાક્ટર કામગીરી રજિસ્ટ્રી",
    "nav_supply_chain": "સપ્લાય ચેઈન બુદ્ધિપ્રતિભા",
    "nav_executive_analytics": "કારોબારી વિશ્લેષણ અને અહેવાલો",
    "nav_fund_mgmt": "ફંડ મેનેજમેન્ટ અને ફાળવણી",
    "nav_ai_engine": "AI જોખમ એન્જિન",
    "nav_compliance": "અનુપાલન અને ઓડિટ ટ્રેઇલ"
  },
  "pa": {
    "gov_india": "Government of India",
    "bharat_sarkar": "ਭਾਰਤ ਸਰਕਾਰ",
    "skip_to_content": "ਮੁੱਖ ਸਮੱਗਰੀ ਤੇ ਜਾਓ",
    "screen_reader": "ਸਕ੍ਰੀਨ ਰੀਡਰ ਪਹੁੰਚ",
    "sitemap": "ਸਾਈਟਮੈਪ",
    "faqs": "ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ",
    "helpdesk": "ਹੈਲਪਡੈਸਕ",
    "contact_us": "ਸੰਪਰਕ ਕਰੋ",
    "mplads_title_1": "ਸੰਸਦ ਮੈਂਬਰ",
    "mplads_title_2": "ਸਥਾਨਕ ਖੇਤਰ ਵਿਕਾਸ ਸਕੀਮ (MPLADS)",
    "mospi_dept": "ਅੰਕੜਾ ਅਤੇ ਪ੍ਰੋਗਰਾਮ ਲਾਗੂਕਰਨ ਮੰਤਰਾਲਾ",
    "gov_of_india_sub": "ਭਾਰਤ ਸਰਕਾਰ",
    "motto_1": "ਸਭਕਾ ਸਾਥ",
    "motto_2": "ਸਭਕਾ ਵਿਕਾਸ",
    "motto_3": "ਸਭਕਾ ਵਿਸ਼ਵਾਸ",
    "motto_4": "ਸਭਕਾ ਪ੍ਰਯਾਸ",
    "nav_home": "ਮੁੱਖ ਪੰਨਾ",
    "nav_about": "MPLADS ਬਾਰੇ",
    "nav_mps": "ਸੰਸਦ ਮੈਂਬਰ",
    "nav_projects": "ਪ੍ਰੋਜੈਕਟ",
    "nav_tenders": "ਟੈਂਡਰ ਅਤੇ ਇਕਰਾਰਨਾਮੇ",
    "nav_vendors": "ਵਿਕਰੇਤਾ",
    "nav_funds": "ਫੰਡ ਪ੍ਰਬੰਧਨ",
    "nav_reports": "ਰਿਪੋਰਟਾਂ",
    "nav_rural_intelligence": "ਪੇਂਡੂ ਖੁਫੀਆ ਜਾਣਕਾਰੀ",
    "nav_contractor_opportunities": "ਠੇਕੇਦਾਰ ਦੇ ਮੌਕੇ",
    "nav_ai_insights": "AI ਇਨਸਾਈਟਸ",
    "nav_citizen": "ਨਾਗਰਿਕ ਕੋਨਾ",
    "search_placeholder": "ਪ੍ਰੋਜੈਕਟ, ਠੇਕੇਦਾਰ, ਟੈਂਡਰ ਖੋਜੋ...",
    "pm_quote": "“MPLADS ਅਧੀਨ ਵਿਕਾਸ ਕਾਰਜ ਜ਼ਮੀਨੀ ਪੱਧਰ 'ਤੇ ਹਰ ਨਾਗਰਿਕ ਲਈ ਬਰਾਬਰ ਤਰੱਕੀ, ਪਾਰਦਰਸ਼ਤਾ ਅਤੇ ਜਮਹੂਰੀ ਸਸ਼ਕਤੀਕਰਨ ਯਕੀਨੀ ਬਣਾਉਣੇ ਚਾਹੀਦੇ ਹਨ।”",
    "pm_name": "ਰਾਹੁਲ ਗਾਂਧੀ",
    "pm_designation": "ਵਿਰੋਧੀ ਧਿਰ ਦੇ ਨੇਤਾ (LoP), ਲੋਕ ਸਭਾ",
    "lop_quote": "“MPLADS ਅਧੀਨ ਵਿਕਾਸ ਕਾਰਜ ਜ਼ਮੀਨੀ ਪੱਧਰ 'ਤੇ ਹਰ ਨਾਗਰਿਕ ਲਈ ਬਰਾਬਰ ਤਰੱਕੀ, ਪਾਰਦਰਸ਼ਤਾ ਅਤੇ ਜਮਹੂਰੀ ਸਸ਼ਕਤੀਕਰਨ ਯਕੀਨੀ ਬਣਾਉਣੇ ਚਾਹੀਦੇ ਹਨ।”",
    "lop_name": "ਰਾਹੁਲ ਗਾਂਧੀ",
    "lop_designation": "ਵਿਰੋਧੀ ਧਿਰ ਦੇ ਨੇਤਾ (LoP), ਲੋਕ ਸਭਾ",
    "peoples_vision": "ਜਨਤਾ ਦਾ ਸੰਕਲਪ",
    "projects_for_progress": "ਤਰੱਕੀ ਲਈ ਪ੍ਰੋਜੈਕਟ",
    "pillar_transparency": "ਪਾਰਦਰਸ਼ਤਾ",
    "pillar_accountability": "ਜਵਾਬਦੇਹੀ",
    "pillar_inclusive": "ਸਮਾਵੇਸ਼ੀ ਵਿਕਾਸ",
    "pillar_lasting_assets": "ਸਥਾਈ ਸੰਪਤੀ",
    "role_overview": "ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
    "role_mp": "ਸੰਸਦ ਮੈਂਬਰ ਦ੍ਰਿਸ਼",
    "role_district": "ਜ਼ਿਲ੍ਹਾ ਅਥਾਰਟੀ",
    "role_contractor": "ਠੇਕੇਦਾਰ",
    "role_vendor": "ਵਿਕਰੇਤਾ",
    "role_ministry": "ਮੰਤਰਾਲਾ",
    "role_citizen": "ਨਾਗਰਿਕ ਦ੍ਰਿਸ਼",
    "district_auth_loc": "ਜ਼ਿਲ੍ਹਾ ਅਥਾਰਟੀ, ਮੁੰਬਈ",
    "total_mps": "ਕੁੱਲ ਸੰਸਦ ਮੈਂਬਰ",
    "total_projects": "ਕੁੱਲ ਪ੍ਰੋਜੈਕਟ",
    "sanctioned_amount": "ਮਨਜ਼ੂਰ ਰਕਮ",
    "contracts_awarded": "ਦਿੱਤੇ ਗਏ ਠੇਕੇ",
    "works_completed": "ਮੁਕੰਮਲ ਕੰਮ",
    "in_progress": "ਪ੍ਰਗਤੀ ਅਧੀਨ",
    "delayed": "ਦੇਰੀ ਨਾਲ",
    "high_risk": "ਉੱਚ ਜੋਖਮ",
    "project_map_india": "ਪ੍ਰੋਜੈਕਟ ਨਕਸ਼ਾ – ਭਾਰਤ",
    "fund_utilization": "ਫੰਡ ਵਰਤੋਂ",
    "recent_projects": "ਹਾਲੀਆ ਪ੍ਰੋਜੈਕਟ",
    "vendor_marketplace": "ਵਿਕਰੇਤਾ ਬਾਜ਼ਾਰ",
    "all_india": "ਸਾਰੇ ਭਾਰਤ ਵਿੱਚ",
    "view_mps": "ਸੰਸਦ ਮੈਂਬਰ ਵੇਖੋ",
    "all_years": "ਸਾਰੇ ਸਾਲ",
    "view_projects": "ਪ੍ਰੋਜੈਕਟ ਵੇਖੋ",
    "view_financials": "ਵਿੱਤੀ ਵੇਰਵੇ ਵੇਖੋ",
    "view_contracts": "ਇਕਰਾਰਨਾਮੇ ਵੇਖੋ",
    "view_details": "ਵੇਰਵੇ ਵੇਖੋ",
    "completed": "ਮੁਕੰਮਲ",
    "view_assets": "ਸੰਪਤੀਆਂ ਵੇਖੋ",
    "view_delayed": "ਦੇਰੀ ਵਾਲੇ ਵੇਖੋ",
    "view_all": "ਸਾਰੇ ਵੇਖੋ",
    "view": "ਵੇਖੋ",
    "investigate": "ਜਾਂਚ ਕਰੋ",
    "project_name": "ਪ੍ਰੋਜੈਕਟ ਦਾ ਨਾਮ",
    "mp": "ਸੰਸਦ ਮੈਂਬਰ",
    "district": "ਜ਼ਿਲ੍ਹਾ",
    "amount": "ਰਕਮ",
    "status": "ਸਥਿਤੀ",
    "action": "ਕਾਰਵਾਈ",
    "contracts_contractors": "ਇਕਰਾਰਨਾਮੇ ਅਤੇ ਠੇਕੇਦਾਰ",
    "contractor_name": "ਠੇਕੇਦਾਰ ਦਾ ਨਾਮ",
    "active_contracts": "ਸਰਗਰਮ ਇਕਰਾਰਨਾਮੇ",
    "total_value": "ਕੁੱਲ ਮੁੱਲ",
    "performance": "ਕਾਰਗੁਜ਼ਾਰੀ",
    "showing_contractors": "50 ਸਰਗਰਮ ਠੇਕੇਦਾਰਾਂ ਵਿੱਚੋਂ 5 ਦਿਖਾ ਰਿਹਾ ਹੈ",
    "contractor_registry_link": "ਠੇਕੇਦਾਰ ਕਾਰਗੁਜ਼ਾਰੀ ਰਜਿਸਟਰੀ →",
    "showing_projects": "28,416 ਆਡਿਟ ਕੀਤੇ ਪ੍ਰੋਜੈਕਟਾਂ ਵਿੱਚੋਂ 5 ਦਿਖਾ ਰਿਹਾ ਹੈ",
    "filter_by_cat": "ਸ਼੍ਰੇਣੀ / ਜ਼ਿਲ੍ਹੇ ਅਨੁਸਾਰ ਫਿਲਟਰ ਕਰੋ →",
    "register_vendor": "ਵਿਕਰੇਤਾ ਰਜਿਸਟਰ ਕਰੋ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "products": "ਉਤਪਾਦ",
    "showing_vendors": "301 ਰਜਿਸਟਰਡ ਵਿਕਰੇਤਾਵਾਂ ਵਿੱਚੋਂ 5 ਦਿਖਾ ਰਿਹਾ ਹੈ",
    "material_intel_link": "ਸਮੱਗਰੀ ਮੁੱਲ ਵਿਸ਼ਲੇਸ਼ਣ →",
    "sanctioned": "ਮਨਜ਼ੂਰਸ਼ੁਦਾ",
    "utilized": "ਵਰਤਿਆ ਗਿਆ",
    "remaining": "ਬਾਕੀ",
    "utilization_rate": "ਵਰਤੋਂ ਦਰ",
    "allocation_disbursed": "ਵੰਡ ਵੰਡੀ ਗਈ",
    "monthly_trend": "ਮਹੀਨਾਵਾਰ ਫੰਡ ਵਰਤੋਂ ਰੁਝਾਨ",
    "annual_trend": "ਸਾਲਾਨਾ ਬਹੁ-ਸਾਲਾ ਰੁਝਾਨ",
    "amount_in_cr": "ਰਕਮ ₹ ਕਰੋੜ ਵਿੱਚ",
    "view_financial_analytics": "ਵਿੱਤੀ ਡੈਸ਼ਬੋਰਡ ਵੇਖੋ",
    "official_mospi_audit": "ਅਧਿਕਾਰਤ MoSPI e-SAKSHI ਆਡਿਟ",
    "project_lifecycle": "ਪ੍ਰੋਜੈਕਟ ਜੀਵਨ ਚੱਕਰ",
    "view_flow": "ਪ੍ਰਵਾਹ ਵੇਖੋ",
    "stage_recommendation": "ਸੰਸਦ ਮੈਂਬਰ ਦੀ ਸਿਫਾਰਸ਼",
    "stage_sanction": "ਜ਼ਿਲ੍ਹਾ ਪ੍ਰਵਾਨਗੀ",
    "stage_tender": "ਟੈਂਡਰ ਪ੍ਰਕਿਰਿਆ",
    "stage_contract": "ਇਕਰਾਰਨਾਮਾ ਅਲਾਟਮੈਂਟ",
    "stage_execution": "ਕੰਮ ਦਾ ਅਮਲ",
    "stage_completion": "ਮੁਕੰਮਲਤਾ ਅਤੇ ਵਰਤੋਂ ਸਰਟੀਫਿਕੇਟ",
    "stage_handover": "ਸੰਪਤੀ ਸੌਂਪਣਾ",
    "lifecycle_workflow_note": "ਮਿਆਰੀ 7-ਪੱਧਰੀ ਕਾਨੂੰਨੀ ਜਾਂਚ ਅਤੇ ਸੌਂਪਣ ਵਰਕਫਲੋ",
    "pending": "ਬਕਾਇਆ",
    "ai_insights_alerts": "AI ਇਨਸਾਈਟਸ ਅਤੇ ਚੇਤਾਵਨੀਆਂ",
    "new_alerts_badge": "5 ਨਵੇਂ",
    "ai_decision_support": "ਫੈਸਲਾ ਸਹਾਇਤਾ AI • ਨਿਰੰਤਰ ਬਹੁ-ਰਿਕਾਰਡ ਆਡਿਟ",
    "rule_engine": "ਨਿਯਮ ਇੰਜਣ v2.4",
    "national_gis_title": "ਰਾਸ਼ਟਰੀ GIS ਅਤੇ ਸੈਟੇਲਾਈਟ ਪ੍ਰੋਜੈਕਟ ਰਾਡਾਰ",
    "national_gis_subtitle": "ਸੰਪਤੀ ਸਥਾਨ, ਸਿੱਧੀ ਜ਼ਮੀਨੀ ਤਸਦੀਕ ਅਤੇ ਅੰਤਰ ਖੋਜ",
    "satellite_mode": "ਸੈਟੇਲਾਈਟ",
    "vector_mode": "ਵੈਕਟਰ",
    "heatmap_mode": "ਜੋਖਮ ਹੀਟਮੈਪ",
    "hierarchy_drilldown": "ਲੜੀਵਾਰ ਵੇਰਵਾ:",
    "open_village_intel": "ਪੇਂਡੂ ਖੁਫੀਆ ਜਾਣਕਾਰੀ ਖੋਲ੍ਹੋ",
    "all_states": "ਸਾਰੇ ਰਾਜ",
    "sih_banner_title": "Smart India Hackathon (SIH) 2026 ਮੁਲਾਂਕਣਕਰਤਾ ਮੋਡ",
    "sih_banner_desc": "19-ਪੜਾਵੀ ਗਾਈਡਡ ਵਾਕਥਰੂ: MoSPI ਡੇਟਾ → ਡਿਜੀਟਲ ਨਕਸ਼ਾ → ਪੇਂਡੂ ਖੁਫੀਆ ਜਾਣਕਾਰੀ → AI ਜੋਖਮ ਇੰਜਣ → ਮਨੁੱਖੀ ਸਮੀਖਿਆ → ਰਿਪੋਰਟਾਂ।",
    "launch_demo_btn": "AI ਜਾਂਚ ਡੈਮੋ ਸ਼ੁਰੂ ਕਰੋ",
    "nav_national_pipeline": "ਰਾਸ਼ਟਰੀ ਡੇਟਾ ਪਾਈਪਲਾਈਨ",
    "nav_procurement_vendors": "ਖਰੀਦ ਅਤੇ ਵਿਕਰੇਤਾ",
    "nav_reports_analytics": "ਰਿਪੋਰਟਾਂ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ",
    "nav_all_projects": "ਸਾਰੇ ਪ੍ਰੋਜੈਕਟ ਡਾਇਰੈਕਟਰੀ",
    "nav_digital_twin": "ਡਿਜੀਟਲ ਟਵਿਨ ਇੰਟਰਐਕਟਿਵ ਨਕਸ਼ਾ",
    "nav_project_splitting": "ਪ੍ਰੋਜੈਕਟ ਵੰਡ ਰਾਡਾਰ",
    "nav_rural_dashboard": "ਪੇਂਡੂ ਖੁਫੀਆ ਡੈਸ਼ਬੋਰਡ",
    "nav_village_explorer": "ਪਿੰਡ ਐਕਸਪਲੋਰਰ ਅਤੇ ਨਕਸ਼ਾ",
    "nav_low_project_villages": "ਘੱਟ ਪ੍ਰੋਜੈਕਟਾਂ ਵਾਲੇ ਪਿੰਡ",
    "nav_data_quality": "ਡੇਟਾ ਗੁਣਵੱਤਾ ਅਤੇ LGD ਆਡਿਟ",
    "nav_upcoming_opportunities": "ਆਗਾਮੀ ਮੌਕੇ ਡੈਸ਼ਬੋਰਡ",
    "nav_my_interests": "ਮੇਰੇ ਦਿਲਚਸਪੀ ਵਾਲੇ ਪ੍ਰੋਜੈਕਟ",
    "nav_express_interest": "ਕੰਮਾਂ ਵਿੱਚ ਦਿਲਚਸਪੀ ਪ੍ਰਗਟ ਕਰੋ",
    "nav_tender_portals": "ਅਧਿਕਾਰਤ ਟੈਂਡਰ ਪੋਰਟਲ",
    "nav_public_tenders": "ਲੋਕ ਨਿਰਮਾਣ ਟੈਂਡਰ",
    "nav_vendor_directory": "ਵਿਕਰੇਤਾ ਡਾਇਰੈਕਟਰੀ ਅਤੇ ਮਾਰਕੀਟਪਲੇਸ",
    "nav_contractor_registry": "ਠੇਕੇਦਾਰ ਕਾਰਗੁਜ਼ਾਰੀ ਰਜਿਸਟਰੀ",
    "nav_supply_chain": "ਸਪਲਾਈ ਚੇਨ ਇੰਟੈਲੀਜੈਂਸ",
    "nav_executive_analytics": "ਕਾਰਜਕਾਰੀ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਰਿਪੋਰਟਾਂ",
    "nav_fund_mgmt": "ਫੰਡ ਪ੍ਰਬੰਧਨ ਅਤੇ ਅਲਾਟਮੈਂਟ",
    "nav_ai_engine": "AI ਜੋਖਮ ਇੰਜਣ",
    "nav_compliance": "ਪਾਲਣਾ ਅਤੇ ਆਡਿਟ ਟ੍ਰੇਲ"
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => { },
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('mplads_lang');
    return (saved as SupportedLanguage) || 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('mplads_lang', lang);
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
